---
title: "Benchmarking frecipes"
author: "Jonathan Kennel"
format: html
---

# Timings *frecipes* vs *recipes*

```{r}
#| echo: false
#| warning: false
#| message: false

library(bench)
library(tibble)
library(data.table)
library(dplyr)
library(collapse)
library(recipes)
library(frecipes)
library(ggbeeswarm)

```

## Creating a recipe

```{r}
#| echo: false
#| warning: false

n <- c(1e3, 1e5, 1e7)
formula <- as.formula(y~x)

results <- bench::press(
  rows = n,
  {
    dat <- data.frame(x = rnorm(rows), 
                      y = 1:rows)
    bench::mark(
      frec = Recipe$new(formula = formula, data = dat),
      rec  = recipe(formula = formula, data = dat),
      check = FALSE
    )
  }
)

results
```

## Add a step

```{r}
#| echo: false
#| warning: false

results <- bench::press(
  rows = n,
  {
    dat <- data.frame(x = rnorm(rows), 
                      y = 1:rows)
    bench::mark(
      frec = Recipe$new(formula = formula, data = dat)$
        add_step(StepCenter$new(x)),
      rec  = {recipe(formula = formula, data = dat) |>
          step_center(x)},
      check = FALSE,
      relative = TRUE
    )
  }
)

results
```



## step_center prep

```{r}
#| echo: false
#| warning: false

results <- bench::press(
  rows = n,
  {
    dat <- data.frame(x = rnorm(rows), 
                      y = 1:rows)
    bench::mark(
      frec = Recipe$new(formula = formula, data = dat)$
        add_step(StepCenter$new(x))$
        prep(),
      rec  = {recipe(formula = formula, data = dat) |>
          step_center(x) |>
          prep()},
      check = FALSE,
      min_iterations = 10,
      relative = TRUE
    )
  }
)

results
```

## step_center bake

```{r}
#| echo: false
#| warning: false

formula <- as.formula(y~x+z)

results <- bench::press(
  rows = n,
  {
    dat <- data.frame(x = rnorm(rows), 
                      y = 1:rows,
                      z = rnorm(rows))
    bench::mark(
      frec = {Recipe$new(formula = formula, data = dat)$
          add_step(StepCenter$new(x, z, fun = fmean))$
          prep()$
          bake()},
      rec  = {recipe(formula = formula, data = dat) |>
          step_center(x, z) |>
          prep() |>
          bake(new_data = NULL)},
      check = FALSE,
      min_iterations = 10,
      relative = TRUE
    )
  }
)

results
```

## step_scale bake

```{r}
#| echo: false
#| warning: false

formula <- as.formula(y~x)

results <- bench::press(
  rows = n,
  {
    dat <- data.frame(x = rnorm(rows), 
                      y = 1:rows,
                      z = rnorm(rows))
    bench::mark(
      frec = {Recipe$new(formula = formula, data = dat)$
          add_step(StepScale$new(x, fun = fsd, n_sd = 2L))$
          prep()$
          bake()},
      rec  = {recipe(formula = formula, data = dat) |>
          step_scale(x, factor = 2L) |>
          prep() |>
          bake(new_data = NULL)},
      check = FALSE,
      relative = TRUE,
      min_iterations = 10
    )
  }
)

results
```


## step_normalize bake

```{r}
#| echo: false
#| warning: false

formula <- as.formula(y~x+z)

results <- bench::press(
  rows = n,
  {
    dat <- data.frame(x = rnorm(rows), 
                      y = rnorm(rows),
                      z = rnorm(rows))
    bench::mark(
      frec = Recipe$new(formula = formula, data = dat)$
        add_step(StepNormalize$new(x,z))$
        prep()$
        bake()
      ,
      rec  = {recipe(formula = formula, data = dat) |>
          step_normalize(x,z) |>
          prep() |>
          bake(new_data = NULL)
      },
      check = FALSE,
      relative = TRUE,
      min_iterations = 10
    )
  }
)

results
```

## step_lag bake

```{r}
#| echo: false
#| warning: false

formula <- as.formula(y~x)

results <- bench::press(
  rows = n,
  {
    dat <- data.frame(x = rnorm(rows), 
                      y = 1:rows,
                      z = rnorm(rows))
    bench::mark(
      frec = {Recipe$new(formula = formula, data = dat)$
          add_step(StepLeadLag$new(x, lag = 1:3))$
          prep()$
          bake()},
      rec  = {recipe(formula = formula, data = dat) |>
          step_lag(x, lag = 1:3) |>
          prep() |>
          bake(new_data = NULL)},
      check = FALSE,
      relative = TRUE,
      min_iterations = 10
    )
  }
)

results
```

## step_distributed_lag bake

```{r}
#| echo: false
#| warning: false

formula <- as.formula(y~x)

results <- bench::press(
  rows = n,
  {
    dat <- data.frame(x = rnorm(rows), 
                      y = 1:rows,
                      z = rnorm(rows))
    bench::mark(
      frec = {Recipe$new(formula = formula, data = dat)$
          add_step(StepDistributedLag$new(x, 
                                          knots = frecipes:::log_lags_arma(5, 100)))$
          prep()$
          bake()},
      rec  = {recipe(formula = formula, data = dat) |>
          hydrorecipes::step_distributed_lag(x, 
                                             knots = frecipes:::log_lags_arma(5, 100)) |>
          prep() |>
          bake(new_data = NULL)},
      check = FALSE,
      relative = TRUE,
      min_iterations = 10
    )
  }
)

results
```

## step_harmonic bake

```{r}
#| echo: false
#| warning: false

formula <- as.formula(y~x)

results <- bench::press(
  rows = n,
  {
    dat <- data.frame(x = rnorm(rows), 
                      y = 1:rows,
                      z = rnorm(rows))
    bench::mark(
      frec = {Recipe$new(formula = formula, data = dat)$
          add_step(StepHarmonic$new(x, 
                                    frequency = c(1,2,3), 
                                    cycle_size = 0.1, 
                                    starting_value = 0))$
          prep()$
          bake()},
      rec  = {recipe(formula = formula, data = dat) |>
          step_harmonic(x, 
                        frequency = c(1,2,3), 
                        cycle_size = 0.1, 
                        starting_val = 0) |>
          prep() |>
          bake(new_data = NULL)},
      check = FALSE,
      relative = TRUE,
      min_iterations = 10
    )
  }
)

results
```

## step_pca bake

```{r}
#| echo: false
#| warning: false

formula <- as.formula(x~a+b+c+d+e+f+g+h+i+j+k+l)

results <- bench::press(
  rows = c(1e2,1e4,1e6),
  {
    dat <- data.frame(x = rnorm(rows), 
                      a = rnorm(rows),
                      b = rnorm(rows),
                      c = rnorm(rows),
                      d = rnorm(rows),
                      e = rnorm(rows),
                      f = rnorm(rows),
                      g = rnorm(rows),
                      h = rnorm(rows),
                      i = rnorm(rows),
                      j = rnorm(rows),
                      k = rnorm(rows),
                      l = rnorm(rows)
    )
    bench::mark(
      frec1 = {Recipe$new(formula = formula, data = dat)$
          add_step(StepPca$new(a,b,c,d,e,f,g,h,i,j,k,l, 
                               n_comp = 12L))$
          prep()$
          bake()},
      frec2 = {Recipe$new(formula = formula, data = dat)$
          add_step(StepPca$new(a,b,c,d,e,f,g,h,i,j,k,l, 
                               n_comp = 5L))$
          prep()$
          bake()},
      frec3 = {Recipe$new(formula = formula, data = dat)$
          add_step(StepPca$new(a,b,c,d,e,f,g,h,i,j,k,l, 
                               n_comp = 12L,
                               center = FALSE,
                               scale = FALSE))$
          prep()$
          bake()},
      frec4 = {Recipe$new(formula = formula, data = dat)$
          add_step(StepPca$new(a,b,c,d,e,f,g,h,i,j,k,l, 
                               n_comp = 5L,
                               center = FALSE,
                               scale = FALSE))$
          prep()$
          bake()},
      rec1  = {recipe(formula = formula, data = dat) |>
          step_pca(a,b,c,d,e,f,g,h,i,j,k,l, 
                   num_comp = 12L, 
                   options = list(center = TRUE, scale. = TRUE)) |>
          prep() |>
          bake(new_data = NULL)},
      rec2  = {recipe(formula = formula, data = dat) |>
          step_pca(a,b,c,d,e,f,g,h,i,j,k,l, 
                   num_comp = 5L, 
                   options = list(center = TRUE, scale. = TRUE)) |>
          prep() |>
          bake(new_data = NULL)},
      rec3  = {recipe(formula = formula, data = dat) |>
          step_pca(a,b,c,d,e,f,g,h,i,j,k,l, 
                   num_comp = 12L) |>
          prep() |>
          bake(new_data = NULL)},
      rec4  = {recipe(formula = formula, data = dat) |>
          step_pca(a,b,c,d,e,f,g,h,i,j,k,l, 
                   num_comp = 5L) |>
          prep() |>
          bake(new_data = NULL)},
      check = FALSE,
      relative = TRUE,
      min_iterations = 1
    )
  }
)

print(results, n = 100)



```

## step_find_interval bake

```{r}
#| echo: false
#| warning: false

formula <- as.formula(y~x)

results <- bench::press(
  rows = n,
  {
    dat <- data.frame(x = rnorm(rows), 
                      y = 1:rows,
                      z = rnorm(rows))
    bench::mark(
      frec = {Recipe$new(formula = formula, data = dat)$
          add_step(StepFindInterval$new(x, vec = c(-0.1, 0, 0.1)))$
          prep()$
          bake()},
      rec  = {recipe(formula = formula, data = dat) |>
          step_cut(x, breaks = c(-0.1, 0, 0.1)) |>
          step_dummy(x) |>
          prep() |>
          bake(new_data = NULL)},
      check = FALSE,
      relative = TRUE,
      min_iterations = 1
    )
  }
)

results


```


## Mulitple steps

```{r}
#| echo: false
#| warning: false


results <- bench::press(
  rows = n,
  {
    dat <- data.frame(x = as.numeric(1:rows), 
                      y = 1:rows)
    bench::mark(
      frec = {Recipe$new(formula = formula, data = dat)$
          add_step(StepLeadLag$new(x, lag = 1:10))$
          add_step(StepHarmonic$new(x, 
                                    frequency = c(1,2,3,4,5), 
                                    cycle_size = 0.1, 
                                    starting_value = 0))$
          add_step(StepCenter$new(x))$
          prep()$
          bake()},
      rec  = {recipe(formula = formula, data = dat) |>
          step_lag(x, lag = 1:10, keep_original_cols = TRUE) |>
          step_harmonic(x, 
                        frequency = c(1,2,3,4,5), 
                        cycle_size = 0.1, 
                        starting_val = 0,
                        keep_original_cols = TRUE) |>
          step_center(x) |>
          prep() |>
          bake(new_data = NULL)},
      check = FALSE,
      relative = TRUE,
      min_iterations = 1
    )
  }
)

results


```


## step_b_spline bake

```{r}
#| echo: false
#| warning: false


results <- bench::press(
  rows = n,
  {
    dat <- data.frame(x = rnorm(rows),
                      y = 1:rows)
    ik <- quantile(dat$x, probs = seq(0, 1, 0.1))
    bk <- ik[c(1, length(ik))]
    ik <- ik[-c(1, length(ik))]
    bench::mark(
      frec = {Recipe$new(formula = formula, data = dat)$
          add_step(StepBSpline$new(x,
                                   internal_knots = ik,
                                   boundary_knots = bk,
                                   degree = 3))$
          prep()$
          bake()},
      rec  = {recipe(formula = formula, data = dat) |>
          step_spline_b(x, deg_free = 13) |>
          prep() |>
          bake(new_data = NULL)},
      check = FALSE,
      relative = TRUE,
      min_iterations = 10
    )
  }
)

results


```


<!-- ```{r} -->

<!-- x <- alloc(1.0, 1e6) # Vector -->

<!-- bench::mark( x %*=% 1.0, x %/=% 1.0,x %-=% 0.0, x %+=% 0.0, 1.0/1.0, check = FALSE) -->


<!-- n <- 1000000 -->
<!-- input <- data.frame(i = 1:n, -->
<!--                     c = sample(letters, n, replace = TRUE), -->
<!--                     f = factor(sample(letters, n, replace = TRUE)), -->
<!--                     d = rnorm(n)) -->
<!-- bench::mark(input[[1]], -->
<!--             unclass(input)[[1]], -->
<!--             get_vars(input, 1),  -->
<!--             get_elem(input, 1, recursive = FALSE), -->
<!--             check = FALSE, relative = TRUE) -->

<!-- initial <- data.frame(z = 1:n) -->
<!-- tmp <- findInterval(input[['f']],c(3,7)) -->
<!-- lst <- as.list(input)  -->
<!-- m   <- as.matrix(input) -->
<!-- dt  <- as.data.table(input) -->
<!-- tbl <- as_tibble(input) -->
<!-- df  <- input -->
<!-- mm  <- qDF(m) -->

<!-- # m <- matrix(rnorm(3e6), ncol = 3) -->
<!-- # df <- qDF(m) -->
<!-- # bench::mark(colMeans(m),as.numeric(colMeans(df)), fmean(m), as.numeric(fmean(df)), check = FALSE) -->

<!-- microbenchmark( -->
<!--   bind_cols(initial, lst, .name_repair = 'minimal'), -->
<!--   bind_cols(initial, dt, .name_repair = 'minimal'), -->
<!--   bind_cols(initial, unclass(dt), .name_repair = 'minimal'), -->
<!--   bind_cols(initial, m, .name_repair = 'minimal'), -->
<!--   bind_cols(initial, tbl, .name_repair = 'minimal'), -->
<!--   bind_cols(initial, df, .name_repair = 'minimal'), -->

<!--   cbind(initial, qDF(lst), stringsAsFactors = FALSE), -->
<!--   cbind(initial, qDF(dt), stringsAsFactors = FALSE), -->
<!--   cbind(initial, qDF(unclass(dt)), stringsAsFactors = FALSE), -->
<!--   cbind(initial, qDF(m), stringsAsFactors = FALSE), -->
<!--   cbind(initial, qDF(tbl), stringsAsFactors = FALSE), -->
<!--   cbind(initial, qDF(df), stringsAsFactors = FALSE), -->

<!--   cbind(initial, (lst), stringsAsFactors = FALSE), -->
<!--   cbind(initial, (dt), stringsAsFactors = FALSE), -->
<!--   cbind(initial, (unclass(dt)), stringsAsFactors = FALSE), -->
<!--   cbind(initial, (m), stringsAsFactors = FALSE), -->
<!--   cbind(initial, (tbl), stringsAsFactors = FALSE), -->
<!--   cbind(initial, (df), stringsAsFactors = FALSE), -->


<!--   initial[['a']] <- m[,1], -->
<!--   cbind(cbind(initial, df), df), -->
<!--   cbind(cbind(initial, qDF(lst)), qDF(lst)), -->
<!--   cbind(cbind(initial, tbl), tbl), -->
<!--   bind_cols(bind_cols(initial, lst), lst, .name_repair = 'minimal'), -->
<!--   times = 3 -->
<!-- ) -->

<!-- bench::mark(   -->
<!--   to_dummy_lst(tmp, 3), -->
<!--   check = FALSE -->
<!-- ) -->

<!-- n <- 5 -->
<!-- microbenchmark::microbenchmark( -->
<!--   to_dummy(tmp, n), -->
<!--   to_dummy2(tmp, n), -->
<!--   to_dummy3(tmp, n), -->
<!--   to_dummy4(tmp, n), -->
<!--   to_dummy5(tmp, n), -->
<!--   to_dummy_list(tmp, n), -->
<!--   # to_dummy6(tmp, n), -->
<!--   # to_dummy_lst(tmp, n, paste0('x', 1:n)), -->
<!--   # cbind(initial,to_dummy_lst2(cbind(tmp, tmp), n, paste0('x', 1:n))), -->
<!--   # to_dummy_df(tmp, n, paste0('x', 1:n)), -->
<!--   times = 3 -->
<!-- ) -->

<!-- bench::mark( -->
<!--   qDF(to_dummy(tmp, 10)), -->
<!--   to_dummy_lst(tmp, 10, paste0('x', 1:10)), -->
<!--   to_dummy_df(tmp, 10, paste0('x', 1:10)), -->
<!--   check = FALSE -->
<!-- ) -->
<!-- n <- 10 -->
<!-- microbenchmark::microbenchmark( -->
<!--   cbind(initial, qDF(to_dummy(tmp, n))), -->
<!--   cbind(initial, qDF(to_dummy3(tmp, n))), -->
<!--   cbind(initial, to_dummy_lst(tmp, n, paste0('x', 1:n))), -->
<!--   cbind(initial, to_dummy_df(tmp, n, paste0('x', 1:n))), -->
<!--   times = 5 -->
<!-- ) -->

<!-- bench::mark( -->
<!--   cbind(initial, qDF(to_dummy(tmp, 6))), -->
<!--   cbind(initial, to_dummy_lst(tmp, 6, paste0('x', 1:6))), -->
<!--   cbind(initial, to_dummy_df(tmp, 6, paste0('x', 1:6))), -->
<!--   check = FALSE -->
<!-- ) -->

<!-- bench::mark( -->
<!--   cbind(initial, (lst), stringsAsFactors = FALSE), -->
<!--   cbind(initial, (df), stringsAsFactors = FALSE), -->
<!--   cbind(initial, (tbl), stringsAsFactors = FALSE), -->
<!--   check = FALSE -->
<!-- ) -->

<!-- str(cbind(initial, (lst), stringsAsFactors = FALSE)) -->
<!-- str(cbind(initial, (df), stringsAsFactors = FALSE)) -->


<!-- n <- 1000000L -->
<!-- m <- as.matrix(1:n) -->
<!-- d <- sample(1:10, 1e5, replace = TRUE) -->

<!-- v <- 1:n -->
<!-- nn <- 10 -->
<!-- microbenchmark::microbenchmark( -->
<!--   m0 <- lag_matrix(m, 1:nn, suffix = 'a', prefix = 'b', n_subset = 1), -->
<!--   m1 <- lag_matrix(m, 1:nn, suffix = 'a', prefix = 'b', n_subset = 5), -->
<!--   m3 <- lag_lead_matrix(v, 1:nn, 1, 0), -->
<!--   m4 <- lag_lead_matrix(v, 1:nn, 5, 0), -->
<!--   times = 3 -->
<!-- ) -->

<!-- bench::mark( -->
<!--   m0 <- lag_matrix(m, 1:nn, suffix = 'a', prefix = 'b', n_subset = 1), -->
<!--   m1 <- lag_matrix(m, 1:nn, suffix = 'a', prefix = 'b', n_subset = 5), -->
<!--   m3 <- lag_lead_matrix(v, 1:nn, 1, 0), -->
<!--   m4 <- lag_lead_matrix(v, 1:nn, 5, 0), -->
<!--   check = FALSE -->
<!-- ) -->



<!-- n <- 10000L -->
<!-- t <- sort(rnorm(n)) -->
<!-- m <- matrix(1:(8*n), ncol = 8) -->
<!-- bench::mark( -->
<!--   h1 <- harmonic(t, c(1,2,4,5)), -->
<!--   h2 <- harmonic_float(t, c(1,2,4,5)), -->
<!--   h3 <- harmonic_field(t, c(1,2,4,5)), -->
<!--   check = FALSE -->
<!-- ) -->

<!-- microbenchmark::microbenchmark( -->
<!--   b <- harmonic(t, c(1,2,4,5, 8, 9)), -->
<!--   a <- harmonic_float(t, c(1,2,4,5, 8, 9)), -->
<!--   c <- harmonic_field(t, c(1,2,4,5, 8, 9)), -->
<!--   times = 3 -->
<!-- ) -->
<!-- ``` -->
