---
title: "Hantush-Jacob leaky aquifer"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Hantush-Jacob leaky aquifer}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, results = "hide", include = FALSE}
library(hydrorecipes)
library(plotly)
set.seed(1)
```

### Hantush-Jacob leaky aquifer (Hantush-Jacob, 1955)

```{r example}

time <- 1:2000
flow_rate <- c(runif(1000, 0, 0.003),
               rep(0.0, 1000))

# high
dat <- data.frame(time = 1:2000, flow_rate = flow_rate)
hj_100 <- recipe(flow_rate~time, dat) |>
  step_aquifer_leaky(time, 
                     flow_rate, 
                     leakage = 100, 
                     radius = 100, 
                     storativity = 1e-6,
                     transmissivity = 1e-4) |> 
  plate()

# medium
hj_200 <- recipe(flow_rate~time, dat) |>
  step_aquifer_leaky(time, 
                     flow_rate, 
                     leakage = 200, 
                     radius = 100, 
                     storativity = 1e-6,
                     transmissivity = 1e-4) |> 
  plate()

# low
hj_1000 <- recipe(flow_rate~time, dat) |>
  step_aquifer_leaky(time, 
                     flow_rate, 
                     leakage = 1000, 
                     radius = 100, 
                     storativity = 1e-6,
                     transmissivity = 1e-4) |> 
  plate()


```


```{r grfplot, echo = FALSE}

hj <- data.frame(time = time, 
                 flow_rate = flow_rate,
                 leakage_high = hj_100$aquifer_leaky,
                 leakage_med = hj_200$aquifer_leaky,
                 leakage_low = hj_1000$aquifer_leaky
)


p1 <- plot_ly(hj, x = ~time, y = ~leakage_high,
              type = "scatter", mode = "lines",
              name = "high") |> 
  add_lines(x = ~time, y = ~leakage_med, name = "medium") |>
  add_lines(x = ~time, y = ~leakage_low, name = "low")

p2 <- plot_ly(hj, x = ~time, y = ~flow_rate,
              type = "scatter", mode = "lines", 
              yaxis = "y1", name = "flow rate")

subplot(p1, p2, shareX = TRUE, nrows = 2)


```

## References

Hantush, M.S. and C.E. Jacob, 1955. Non-steady radial flow in an infinite leaky aquifer, Am. Geophys. Union Trans., vol. 36, no. 1, pp. 95-100.

Prodanoff, J.H.A., Mansur, W.J. and Mascarenhas, F.C.B., 2006. Numerical evaluation of Theis and Hantush-Jacob well functions. Journal of hydrology, 318(1-4), pp.173-183.
