// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppThread.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// b_spline_list
Rcpp::List b_spline_list(const arma::vec& x, const unsigned int df, const unsigned int degree, const arma::vec& internal_knots, const arma::vec& boundary_knots, const bool complete_basis, const bool periodic, const unsigned int derivs, const bool integral);
RcppExport SEXP _frecipes_b_spline_list(SEXP xSEXP, SEXP dfSEXP, SEXP degreeSEXP, SEXP internal_knotsSEXP, SEXP boundary_knotsSEXP, SEXP complete_basisSEXP, SEXP periodicSEXP, SEXP derivsSEXP, SEXP integralSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type df(dfSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type degree(degreeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type internal_knots(internal_knotsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type boundary_knots(boundary_knotsSEXP);
    Rcpp::traits::input_parameter< const bool >::type complete_basis(complete_basisSEXP);
    Rcpp::traits::input_parameter< const bool >::type periodic(periodicSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type derivs(derivsSEXP);
    Rcpp::traits::input_parameter< const bool >::type integral(integralSEXP);
    rcpp_result_gen = Rcpp::wrap(b_spline_list(x, df, degree, internal_knots, boundary_knots, complete_basis, periodic, derivs, integral));
    return rcpp_result_gen;
END_RCPP
}
// b_spline_list2
Rcpp::List b_spline_list2(const arma::vec& x, const unsigned int df, const unsigned int degree, const arma::vec& internal_knots, const arma::vec& boundary_knots, const bool complete_basis, const bool periodic, const unsigned int derivs, const bool integral);
RcppExport SEXP _frecipes_b_spline_list2(SEXP xSEXP, SEXP dfSEXP, SEXP degreeSEXP, SEXP internal_knotsSEXP, SEXP boundary_knotsSEXP, SEXP complete_basisSEXP, SEXP periodicSEXP, SEXP derivsSEXP, SEXP integralSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type df(dfSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type degree(degreeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type internal_knots(internal_knotsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type boundary_knots(boundary_knotsSEXP);
    Rcpp::traits::input_parameter< const bool >::type complete_basis(complete_basisSEXP);
    Rcpp::traits::input_parameter< const bool >::type periodic(periodicSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type derivs(derivsSEXP);
    Rcpp::traits::input_parameter< const bool >::type integral(integralSEXP);
    rcpp_result_gen = Rcpp::wrap(b_spline_list2(x, df, degree, internal_knots, boundary_knots, complete_basis, periodic, derivs, integral));
    return rcpp_result_gen;
END_RCPP
}
// b_spline_list3
std::list<Eigen::VectorXd> b_spline_list3(const arma::vec& x, const unsigned int df, const unsigned int degree, const arma::vec& internal_knots, const arma::vec& boundary_knots, const bool complete_basis, const bool periodic, const unsigned int derivs, const bool integral);
RcppExport SEXP _frecipes_b_spline_list3(SEXP xSEXP, SEXP dfSEXP, SEXP degreeSEXP, SEXP internal_knotsSEXP, SEXP boundary_knotsSEXP, SEXP complete_basisSEXP, SEXP periodicSEXP, SEXP derivsSEXP, SEXP integralSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type df(dfSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type degree(degreeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type internal_knots(internal_knotsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type boundary_knots(boundary_knotsSEXP);
    Rcpp::traits::input_parameter< const bool >::type complete_basis(complete_basisSEXP);
    Rcpp::traits::input_parameter< const bool >::type periodic(periodicSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type derivs(derivsSEXP);
    Rcpp::traits::input_parameter< const bool >::type integral(integralSEXP);
    rcpp_result_gen = Rcpp::wrap(b_spline_list3(x, df, degree, internal_knots, boundary_knots, complete_basis, periodic, derivs, integral));
    return rcpp_result_gen;
END_RCPP
}
// log_lags_arma
arma::vec log_lags_arma(arma::uword n, arma::uword max_lag);
RcppExport SEXP _frecipes_log_lags_arma(SEXP nSEXP, SEXP max_lagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uword >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type max_lag(max_lagSEXP);
    rcpp_result_gen = Rcpp::wrap(log_lags_arma(n, max_lag));
    return rcpp_result_gen;
END_RCPP
}
// distributed_lag_thread
Eigen::MatrixXd distributed_lag_thread(const Eigen::VectorXd& x, const Eigen::MatrixXd& bl, int n_thread);
RcppExport SEXP _frecipes_distributed_lag_thread(SEXP xSEXP, SEXP blSEXP, SEXP n_threadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type bl(blSEXP);
    Rcpp::traits::input_parameter< int >::type n_thread(n_threadSEXP);
    rcpp_result_gen = Rcpp::wrap(distributed_lag_thread(x, bl, n_thread));
    return rcpp_result_gen;
END_RCPP
}
// convolve_eigen
Eigen::VectorXd convolve_eigen(const Eigen::VectorXd& x, const Eigen::RowVectorXd& y);
RcppExport SEXP _frecipes_convolve_eigen(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Eigen::RowVectorXd& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(convolve_eigen(x, y));
    return rcpp_result_gen;
END_RCPP
}
// distributed_lag_eigen
Rcpp::List distributed_lag_eigen(Eigen::Map<Eigen::VectorXd> x, Eigen::Map<Eigen::MatrixXd> bl);
RcppExport SEXP _frecipes_distributed_lag_eigen(SEXP xSEXP, SEXP blSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd> >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type bl(blSEXP);
    rcpp_result_gen = Rcpp::wrap(distributed_lag_eigen(x, bl));
    return rcpp_result_gen;
END_RCPP
}
// distributed_lag_thread_eigen
List distributed_lag_thread_eigen(Eigen::Map<Eigen::VectorXd> x, Eigen::Map<Eigen::MatrixXd> bl, int lag_max, int n_subset, int n_shift, int n_thread);
RcppExport SEXP _frecipes_distributed_lag_thread_eigen(SEXP xSEXP, SEXP blSEXP, SEXP lag_maxSEXP, SEXP n_subsetSEXP, SEXP n_shiftSEXP, SEXP n_threadSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd> >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type bl(blSEXP);
    Rcpp::traits::input_parameter< int >::type lag_max(lag_maxSEXP);
    Rcpp::traits::input_parameter< int >::type n_subset(n_subsetSEXP);
    Rcpp::traits::input_parameter< int >::type n_shift(n_shiftSEXP);
    Rcpp::traits::input_parameter< int >::type n_thread(n_threadSEXP);
    rcpp_result_gen = Rcpp::wrap(distributed_lag_thread_eigen(x, bl, lag_max, n_subset, n_shift, n_thread));
    return rcpp_result_gen;
END_RCPP
}
// distributed_lag_list
Rcpp::List distributed_lag_list(Eigen::Map<Eigen::VectorXd> x, arma::uword n_lag, arma::uword max_lag, const unsigned int df, const unsigned int degree, const arma::vec& internal_knots, const arma::vec& boundary_knots, const bool complete_basis, const bool periodic, const unsigned int derivs, const bool integral);
RcppExport SEXP _frecipes_distributed_lag_list(SEXP xSEXP, SEXP n_lagSEXP, SEXP max_lagSEXP, SEXP dfSEXP, SEXP degreeSEXP, SEXP internal_knotsSEXP, SEXP boundary_knotsSEXP, SEXP complete_basisSEXP, SEXP periodicSEXP, SEXP derivsSEXP, SEXP integralSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd> >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type n_lag(n_lagSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type max_lag(max_lagSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type df(dfSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type degree(degreeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type internal_knots(internal_knotsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type boundary_knots(boundary_knotsSEXP);
    Rcpp::traits::input_parameter< const bool >::type complete_basis(complete_basisSEXP);
    Rcpp::traits::input_parameter< const bool >::type periodic(periodicSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type derivs(derivsSEXP);
    Rcpp::traits::input_parameter< const bool >::type integral(integralSEXP);
    rcpp_result_gen = Rcpp::wrap(distributed_lag_list(x, n_lag, max_lag, df, degree, internal_knots, boundary_knots, complete_basis, periodic, derivs, integral));
    return rcpp_result_gen;
END_RCPP
}
// distributed_lag_list2
std::list<Eigen::VectorXd> distributed_lag_list2(Eigen::Map<Eigen::VectorXd> x, arma::uword n_lag, arma::uword max_lag, const unsigned int df, const unsigned int degree, const arma::vec& internal_knots, const arma::vec& boundary_knots, const bool complete_basis, const bool periodic, const unsigned int derivs, const bool integral);
RcppExport SEXP _frecipes_distributed_lag_list2(SEXP xSEXP, SEXP n_lagSEXP, SEXP max_lagSEXP, SEXP dfSEXP, SEXP degreeSEXP, SEXP internal_knotsSEXP, SEXP boundary_knotsSEXP, SEXP complete_basisSEXP, SEXP periodicSEXP, SEXP derivsSEXP, SEXP integralSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd> >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type n_lag(n_lagSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type max_lag(max_lagSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type df(dfSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type degree(degreeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type internal_knots(internal_knotsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type boundary_knots(boundary_knotsSEXP);
    Rcpp::traits::input_parameter< const bool >::type complete_basis(complete_basisSEXP);
    Rcpp::traits::input_parameter< const bool >::type periodic(periodicSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type derivs(derivsSEXP);
    Rcpp::traits::input_parameter< const bool >::type integral(integralSEXP);
    rcpp_result_gen = Rcpp::wrap(distributed_lag_list2(x, n_lag, max_lag, df, degree, internal_knots, boundary_knots, complete_basis, periodic, derivs, integral));
    return rcpp_result_gen;
END_RCPP
}
// distributed_lag_list3
Rcpp::List distributed_lag_list3(Eigen::VectorXd x, arma::uword n_lag, arma::uword max_lag, const unsigned int df, const unsigned int degree, const arma::vec& internal_knots, const arma::vec& boundary_knots, const bool complete_basis, const bool periodic, const unsigned int derivs, const bool integral);
RcppExport SEXP _frecipes_distributed_lag_list3(SEXP xSEXP, SEXP n_lagSEXP, SEXP max_lagSEXP, SEXP dfSEXP, SEXP degreeSEXP, SEXP internal_knotsSEXP, SEXP boundary_knotsSEXP, SEXP complete_basisSEXP, SEXP periodicSEXP, SEXP derivsSEXP, SEXP integralSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type n_lag(n_lagSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type max_lag(max_lagSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type df(dfSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type degree(degreeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type internal_knots(internal_knotsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type boundary_knots(boundary_knotsSEXP);
    Rcpp::traits::input_parameter< const bool >::type complete_basis(complete_basisSEXP);
    Rcpp::traits::input_parameter< const bool >::type periodic(periodicSEXP);
    Rcpp::traits::input_parameter< const unsigned int >::type derivs(derivsSEXP);
    Rcpp::traits::input_parameter< const bool >::type integral(integralSEXP);
    rcpp_result_gen = Rcpp::wrap(distributed_lag_list3(x, n_lag, max_lag, df, degree, internal_knots, boundary_knots, complete_basis, periodic, derivs, integral));
    return rcpp_result_gen;
END_RCPP
}
// fft_matrix
Eigen::MatrixXcd fft_matrix(Eigen::MatrixXd x, size_t n_new);
RcppExport SEXP _frecipes_fft_matrix(SEXP xSEXP, SEXP n_newSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type x(xSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_new(n_newSEXP);
    rcpp_result_gen = Rcpp::wrap(fft_matrix(x, n_new));
    return rcpp_result_gen;
END_RCPP
}
// convolve_vec
Eigen::VectorXd convolve_vec(Eigen::VectorXd x, Eigen::VectorXd y);
RcppExport SEXP _frecipes_convolve_vec(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(convolve_vec(x, y));
    return rcpp_result_gen;
END_RCPP
}
// convolve_filter
Eigen::VectorXd convolve_filter(const Eigen::VectorXd& x, const Eigen::VectorXd& y, bool remove_partial, bool reverse);
RcppExport SEXP _frecipes_convolve_filter(SEXP xSEXP, SEXP ySEXP, SEXP remove_partialSEXP, SEXP reverseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< bool >::type remove_partial(remove_partialSEXP);
    Rcpp::traits::input_parameter< bool >::type reverse(reverseSEXP);
    rcpp_result_gen = Rcpp::wrap(convolve_filter(x, y, remove_partial, reverse));
    return rcpp_result_gen;
END_RCPP
}
// convolve_overlap_add
Eigen::VectorXd convolve_overlap_add(Eigen::VectorXd& x, Eigen::VectorXd& y);
RcppExport SEXP _frecipes_convolve_overlap_add(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd& >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(convolve_overlap_add(x, y));
    return rcpp_result_gen;
END_RCPP
}
// convolve_overlap_save
Eigen::VectorXd convolve_overlap_save(Eigen::VectorXd& x, Eigen::VectorXd& y);
RcppExport SEXP _frecipes_convolve_overlap_save(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd& >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(convolve_overlap_save(x, y));
    return rcpp_result_gen;
END_RCPP
}
// convolve_overlap_save_list
List convolve_overlap_save_list(Eigen::VectorXd& x, List y);
RcppExport SEXP _frecipes_convolve_overlap_save_list(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd& >::type x(xSEXP);
    Rcpp::traits::input_parameter< List >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(convolve_overlap_save_list(x, y));
    return rcpp_result_gen;
END_RCPP
}
// convolve_tf
Eigen::VectorXd convolve_tf(Eigen::VectorXd x, Eigen::VectorXcd y);
RcppExport SEXP _frecipes_convolve_tf(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXcd >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(convolve_tf(x, y));
    return rcpp_result_gen;
END_RCPP
}
// convolve_matrix
Eigen::MatrixXd convolve_matrix(const Eigen::VectorXd& x, const Eigen::MatrixXd& y, const bool remove_partial, const bool reverse);
RcppExport SEXP _frecipes_convolve_matrix(SEXP xSEXP, SEXP ySEXP, SEXP remove_partialSEXP, SEXP reverseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const bool >::type remove_partial(remove_partialSEXP);
    Rcpp::traits::input_parameter< const bool >::type reverse(reverseSEXP);
    rcpp_result_gen = Rcpp::wrap(convolve_matrix(x, y, remove_partial, reverse));
    return rcpp_result_gen;
END_RCPP
}
// convolve_list
Rcpp::List convolve_list(const Eigen::VectorXd& x, const List y, const bool remove_partial, const bool reverse);
RcppExport SEXP _frecipes_convolve_list(SEXP xSEXP, SEXP ySEXP, SEXP remove_partialSEXP, SEXP reverseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const List >::type y(ySEXP);
    Rcpp::traits::input_parameter< const bool >::type remove_partial(remove_partialSEXP);
    Rcpp::traits::input_parameter< const bool >::type reverse(reverseSEXP);
    rcpp_result_gen = Rcpp::wrap(convolve_list(x, y, remove_partial, reverse));
    return rcpp_result_gen;
END_RCPP
}
// convolve_list2
std::list<Eigen::VectorXd> convolve_list2(const Eigen::VectorXd& x, const std::list<Eigen::VectorXd> y, const bool remove_partial, const bool reverse);
RcppExport SEXP _frecipes_convolve_list2(SEXP xSEXP, SEXP ySEXP, SEXP remove_partialSEXP, SEXP reverseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const std::list<Eigen::VectorXd> >::type y(ySEXP);
    Rcpp::traits::input_parameter< const bool >::type remove_partial(remove_partialSEXP);
    Rcpp::traits::input_parameter< const bool >::type reverse(reverseSEXP);
    rcpp_result_gen = Rcpp::wrap(convolve_list2(x, y, remove_partial, reverse));
    return rcpp_result_gen;
END_RCPP
}
// multiply_ffts
Eigen::MatrixXcd multiply_ffts(Eigen::MatrixXcd& x);
RcppExport SEXP _frecipes_multiply_ffts(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXcd& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(multiply_ffts(x));
    return rcpp_result_gen;
END_RCPP
}
// fill_lower_left
Eigen::MatrixXcd fill_lower_left(Eigen::MatrixXcd& x, size_t start);
RcppExport SEXP _frecipes_fill_lower_left(SEXP xSEXP, SEXP startSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXcd& >::type x(xSEXP);
    Rcpp::traits::input_parameter< size_t >::type start(startSEXP);
    rcpp_result_gen = Rcpp::wrap(fill_lower_left(x, start));
    return rcpp_result_gen;
END_RCPP
}
// spec_pgram
Eigen::MatrixXcd spec_pgram(Eigen::MatrixXd& x, const Eigen::VectorXi& spans, bool detrend, bool demean, double taper);
RcppExport SEXP _frecipes_spec_pgram(SEXP xSEXP, SEXP spansSEXP, SEXP detrendSEXP, SEXP demeanSEXP, SEXP taperSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi& >::type spans(spansSEXP);
    Rcpp::traits::input_parameter< bool >::type detrend(detrendSEXP);
    Rcpp::traits::input_parameter< bool >::type demean(demeanSEXP);
    Rcpp::traits::input_parameter< double >::type taper(taperSEXP);
    rcpp_result_gen = Rcpp::wrap(spec_pgram(x, spans, detrend, demean, taper));
    return rcpp_result_gen;
END_RCPP
}
// spec_welch
Eigen::MatrixXcd spec_welch(Eigen::MatrixXd& x, size_t length_subset, double overlap, Eigen::VectorXd window);
RcppExport SEXP _frecipes_spec_welch(SEXP xSEXP, SEXP length_subsetSEXP, SEXP overlapSEXP, SEXP windowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd& >::type x(xSEXP);
    Rcpp::traits::input_parameter< size_t >::type length_subset(length_subsetSEXP);
    Rcpp::traits::input_parameter< double >::type overlap(overlapSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type window(windowSEXP);
    rcpp_result_gen = Rcpp::wrap(spec_welch(x, length_subset, overlap, window));
    return rcpp_result_gen;
END_RCPP
}
// solve_cplx_parallel
Eigen::MatrixXcd solve_cplx_parallel(const Eigen::MatrixXcd& x);
RcppExport SEXP _frecipes_solve_cplx_parallel(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXcd& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(solve_cplx_parallel(x));
    return rcpp_result_gen;
END_RCPP
}
// solve_cplx_irr
Eigen::MatrixXcd solve_cplx_irr(Eigen::MatrixXcd& x, size_t n_groups);
RcppExport SEXP _frecipes_solve_cplx_irr(SEXP xSEXP, SEXP n_groupsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXcd& >::type x(xSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_groups(n_groupsSEXP);
    rcpp_result_gen = Rcpp::wrap(solve_cplx_irr(x, n_groups));
    return rcpp_result_gen;
END_RCPP
}
// ordinary_coherence_phase
Eigen::MatrixXd ordinary_coherence_phase(const Eigen::ArrayXXcd& x);
RcppExport SEXP _frecipes_ordinary_coherence_phase(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::ArrayXXcd& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(ordinary_coherence_phase(x));
    return rcpp_result_gen;
END_RCPP
}
// transfer_pgram_smooth
Eigen::MatrixXcd transfer_pgram_smooth(Eigen::MatrixXd& x, const Eigen::VectorXi& spans, bool detrend, bool demean, double taper, double power, size_t n_groups);
RcppExport SEXP _frecipes_transfer_pgram_smooth(SEXP xSEXP, SEXP spansSEXP, SEXP detrendSEXP, SEXP demeanSEXP, SEXP taperSEXP, SEXP powerSEXP, SEXP n_groupsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi& >::type spans(spansSEXP);
    Rcpp::traits::input_parameter< bool >::type detrend(detrendSEXP);
    Rcpp::traits::input_parameter< bool >::type demean(demeanSEXP);
    Rcpp::traits::input_parameter< double >::type taper(taperSEXP);
    Rcpp::traits::input_parameter< double >::type power(powerSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_groups(n_groupsSEXP);
    rcpp_result_gen = Rcpp::wrap(transfer_pgram_smooth(x, spans, detrend, demean, taper, power, n_groups));
    return rcpp_result_gen;
END_RCPP
}
// transfer_pgram
Eigen::MatrixXcd transfer_pgram(Eigen::MatrixXd& x, const Eigen::VectorXi& spans, bool detrend, bool demean, double taper);
RcppExport SEXP _frecipes_transfer_pgram(SEXP xSEXP, SEXP spansSEXP, SEXP detrendSEXP, SEXP demeanSEXP, SEXP taperSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXi& >::type spans(spansSEXP);
    Rcpp::traits::input_parameter< bool >::type detrend(detrendSEXP);
    Rcpp::traits::input_parameter< bool >::type demean(demeanSEXP);
    Rcpp::traits::input_parameter< double >::type taper(taperSEXP);
    rcpp_result_gen = Rcpp::wrap(transfer_pgram(x, spans, detrend, demean, taper));
    return rcpp_result_gen;
END_RCPP
}
// transfer_welch
Eigen::MatrixXcd transfer_welch(Eigen::MatrixXd& x, size_t length_subset, double overlap, Eigen::VectorXd window);
RcppExport SEXP _frecipes_transfer_welch(SEXP xSEXP, SEXP length_subsetSEXP, SEXP overlapSEXP, SEXP windowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd& >::type x(xSEXP);
    Rcpp::traits::input_parameter< size_t >::type length_subset(length_subsetSEXP);
    Rcpp::traits::input_parameter< double >::type overlap(overlapSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type window(windowSEXP);
    rcpp_result_gen = Rcpp::wrap(transfer_welch(x, length_subset, overlap, window));
    return rcpp_result_gen;
END_RCPP
}
// index_from_i_j
size_t index_from_i_j(size_t i, size_t j, size_t n_col);
RcppExport SEXP _frecipes_index_from_i_j(SEXP iSEXP, SEXP jSEXP, SEXP n_colSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< size_t >::type i(iSEXP);
    Rcpp::traits::input_parameter< size_t >::type j(jSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_col(n_colSEXP);
    rcpp_result_gen = Rcpp::wrap(index_from_i_j(i, j, n_col));
    return rcpp_result_gen;
END_RCPP
}
// get_column_number
size_t get_column_number(size_t n);
RcppExport SEXP _frecipes_get_column_number(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< size_t >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(get_column_number(n));
    return rcpp_result_gen;
END_RCPP
}
// index_from_j_i
size_t index_from_j_i(size_t i, size_t j, size_t n_col);
RcppExport SEXP _frecipes_index_from_j_i(SEXP iSEXP, SEXP jSEXP, SEXP n_colSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< size_t >::type i(iSEXP);
    Rcpp::traits::input_parameter< size_t >::type j(jSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_col(n_colSEXP);
    rcpp_result_gen = Rcpp::wrap(index_from_j_i(i, j, n_col));
    return rcpp_result_gen;
END_RCPP
}
// next_n_eigen
size_t next_n_eigen(size_t n);
RcppExport SEXP _frecipes_next_n_eigen(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< size_t >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(next_n_eigen(n));
    return rcpp_result_gen;
END_RCPP
}
// pad_vector
Eigen::VectorXd pad_vector(Eigen::VectorXd x, size_t n_old, size_t n_new);
RcppExport SEXP _frecipes_pad_vector(SEXP xSEXP, SEXP n_oldSEXP, SEXP n_newSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type x(xSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_old(n_oldSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_new(n_newSEXP);
    rcpp_result_gen = Rcpp::wrap(pad_vector(x, n_old, n_new));
    return rcpp_result_gen;
END_RCPP
}
// detrend_matrix
Eigen::MatrixXd detrend_matrix(const Eigen::MatrixXd& x);
RcppExport SEXP _frecipes_detrend_matrix(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(detrend_matrix(x));
    return rcpp_result_gen;
END_RCPP
}
// demean_matrix
Eigen::MatrixXd demean_matrix(const Eigen::MatrixXd& x);
RcppExport SEXP _frecipes_demean_matrix(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(demean_matrix(x));
    return rcpp_result_gen;
END_RCPP
}
// detrend_and_demean_matrix
Eigen::MatrixXd detrend_and_demean_matrix(const Eigen::MatrixXd& x, bool detrend, bool demean);
RcppExport SEXP _frecipes_detrend_and_demean_matrix(SEXP xSEXP, SEXP detrendSEXP, SEXP demeanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type detrend(detrendSEXP);
    Rcpp::traits::input_parameter< bool >::type demean(demeanSEXP);
    rcpp_result_gen = Rcpp::wrap(detrend_and_demean_matrix(x, detrend, demean));
    return rcpp_result_gen;
END_RCPP
}
// modified_daniell
Eigen::VectorXd modified_daniell(Eigen::VectorXi spans);
RcppExport SEXP _frecipes_modified_daniell(SEXP spansSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type spans(spansSEXP);
    rcpp_result_gen = Rcpp::wrap(modified_daniell(spans));
    return rcpp_result_gen;
END_RCPP
}
// kernel_apply
Eigen::MatrixXcd kernel_apply(Eigen::MatrixXcd& x, Eigen::VectorXd& y);
RcppExport SEXP _frecipes_kernel_apply(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXcd& >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(kernel_apply(x, y));
    return rcpp_result_gen;
END_RCPP
}
// spec_taper
Eigen::VectorXd spec_taper(size_t n_row, double p);
RcppExport SEXP _frecipes_spec_taper(SEXP n_rowSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< size_t >::type n_row(n_rowSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(spec_taper(n_row, p));
    return rcpp_result_gen;
END_RCPP
}
// make_groups
Eigen::VectorXi make_groups(size_t n_groups, size_t n);
RcppExport SEXP _frecipes_make_groups(SEXP n_groupsSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< size_t >::type n_groups(n_groupsSEXP);
    Rcpp::traits::input_parameter< size_t >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(make_groups(n_groups, n));
    return rcpp_result_gen;
END_RCPP
}
// power_spaced
Eigen::ArrayXd power_spaced(size_t n, double min, double max, double power);
RcppExport SEXP _frecipes_power_spaced(SEXP nSEXP, SEXP minSEXP, SEXP maxSEXP, SEXP powerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< size_t >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type min(minSEXP);
    Rcpp::traits::input_parameter< double >::type max(maxSEXP);
    Rcpp::traits::input_parameter< double >::type power(powerSEXP);
    rcpp_result_gen = Rcpp::wrap(power_spaced(n, min, max, power));
    return rcpp_result_gen;
END_RCPP
}
// group_frequency
Eigen::VectorXd group_frequency(Eigen::ArrayXd frequencies, size_t n_groups);
RcppExport SEXP _frecipes_group_frequency(SEXP frequenciesSEXP, SEXP n_groupsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::ArrayXd >::type frequencies(frequenciesSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_groups(n_groupsSEXP);
    rcpp_result_gen = Rcpp::wrap(group_frequency(frequencies, n_groups));
    return rcpp_result_gen;
END_RCPP
}
// determine_frequency
Eigen::VectorXd determine_frequency(size_t n);
RcppExport SEXP _frecipes_determine_frequency(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< size_t >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(determine_frequency(n));
    return rcpp_result_gen;
END_RCPP
}
// check_ffts
Eigen::MatrixXcd check_ffts(Eigen::MatrixXcd& x, double cutoff);
RcppExport SEXP _frecipes_check_ffts(SEXP xSEXP, SEXP cutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXcd& >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type cutoff(cutoffSEXP);
    rcpp_result_gen = Rcpp::wrap(check_ffts(x, cutoff));
    return rcpp_result_gen;
END_RCPP
}
// which_indices
Eigen::VectorXi which_indices(const Eigen::VectorXd& x, const Eigen::VectorXd& knots);
RcppExport SEXP _frecipes_which_indices(SEXP xSEXP, SEXP knotsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type knots(knotsSEXP);
    rcpp_result_gen = Rcpp::wrap(which_indices(x, knots));
    return rcpp_result_gen;
END_RCPP
}
// window_hann
Eigen::VectorXd window_hann(size_t n);
RcppExport SEXP _frecipes_window_hann(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< size_t >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(window_hann(n));
    return rcpp_result_gen;
END_RCPP
}
// window_tukey
Eigen::VectorXd window_tukey(size_t n, double r);
RcppExport SEXP _frecipes_window_tukey(SEXP nSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< size_t >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(window_tukey(n, r));
    return rcpp_result_gen;
END_RCPP
}
// window_hann_cplx
Eigen::VectorXcd window_hann_cplx(size_t n);
RcppExport SEXP _frecipes_window_hann_cplx(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< size_t >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(window_hann_cplx(n));
    return rcpp_result_gen;
END_RCPP
}
// window_rectangle
Eigen::VectorXd window_rectangle(size_t n);
RcppExport SEXP _frecipes_window_rectangle(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< size_t >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(window_rectangle(n));
    return rcpp_result_gen;
END_RCPP
}
// window_first_deriv
Eigen::ArrayXd window_first_deriv(size_t n, double a0, double a1, double a2, double a3);
RcppExport SEXP _frecipes_window_first_deriv(SEXP nSEXP, SEXP a0SEXP, SEXP a1SEXP, SEXP a2SEXP, SEXP a3SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< size_t >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type a1(a1SEXP);
    Rcpp::traits::input_parameter< double >::type a2(a2SEXP);
    Rcpp::traits::input_parameter< double >::type a3(a3SEXP);
    rcpp_result_gen = Rcpp::wrap(window_first_deriv(n, a0, a1, a2, a3));
    return rcpp_result_gen;
END_RCPP
}
// window_nuttall
Eigen::ArrayXd window_nuttall(size_t n);
RcppExport SEXP _frecipes_window_nuttall(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< size_t >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(window_nuttall(n));
    return rcpp_result_gen;
END_RCPP
}
// window_blackman_nuttall
Eigen::ArrayXd window_blackman_nuttall(size_t n);
RcppExport SEXP _frecipes_window_blackman_nuttall(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< size_t >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(window_blackman_nuttall(n));
    return rcpp_result_gen;
END_RCPP
}
// window_blackman_harris
Eigen::ArrayXd window_blackman_harris(size_t n);
RcppExport SEXP _frecipes_window_blackman_harris(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< size_t >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(window_blackman_harris(n));
    return rcpp_result_gen;
END_RCPP
}
// window_scale
double window_scale(Eigen::VectorXd window, size_t n_new, size_t n_fft);
RcppExport SEXP _frecipes_window_scale(SEXP windowSEXP, SEXP n_newSEXP, SEXP n_fftSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type window(windowSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_new(n_newSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_fft(n_fftSEXP);
    rcpp_result_gen = Rcpp::wrap(window_scale(window, n_new, n_fft));
    return rcpp_result_gen;
END_RCPP
}
// harmonic_list
List harmonic_list(const NumericVector& time, const NumericVector& frequency, const double start, const double cycle_size);
RcppExport SEXP _frecipes_harmonic_list(SEXP timeSEXP, SEXP frequencySEXP, SEXP startSEXP, SEXP cycle_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type frequency(frequencySEXP);
    Rcpp::traits::input_parameter< const double >::type start(startSEXP);
    Rcpp::traits::input_parameter< const double >::type cycle_size(cycle_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(harmonic_list(time, frequency, start, cycle_size));
    return rcpp_result_gen;
END_RCPP
}
// check_lag
int check_lag(int n, int lag, int n_shift);
RcppExport SEXP _frecipes_check_lag(SEXP nSEXP, SEXP lagSEXP, SEXP n_shiftSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< int >::type n_shift(n_shiftSEXP);
    rcpp_result_gen = Rcpp::wrap(check_lag(n, lag, n_shift));
    return rcpp_result_gen;
END_RCPP
}
// get_length
int get_length(int n, int n_subset);
RcppExport SEXP _frecipes_get_length(SEXP nSEXP, SEXP n_subsetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type n_subset(n_subsetSEXP);
    rcpp_result_gen = Rcpp::wrap(get_length(n, n_subset));
    return rcpp_result_gen;
END_RCPP
}
// get_start
int get_start(int n_out, int lag, int n_subset);
RcppExport SEXP _frecipes_get_start(SEXP n_outSEXP, SEXP lagSEXP, SEXP n_subsetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_out(n_outSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< int >::type n_subset(n_subsetSEXP);
    rcpp_result_gen = Rcpp::wrap(get_start(n_out, lag, n_subset));
    return rcpp_result_gen;
END_RCPP
}
// get_end
int get_end(int n, int n_out, int lag, int n_subset);
RcppExport SEXP _frecipes_get_end(SEXP nSEXP, SEXP n_outSEXP, SEXP lagSEXP, SEXP n_subsetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type n_out(n_outSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< int >::type n_subset(n_subsetSEXP);
    rcpp_result_gen = Rcpp::wrap(get_end(n, n_out, lag, n_subset));
    return rcpp_result_gen;
END_RCPP
}
// shift_subset
NumericVector shift_subset(const NumericVector& x, size_t lag, size_t n_subset, size_t n_shift);
RcppExport SEXP _frecipes_shift_subset(SEXP xSEXP, SEXP lagSEXP, SEXP n_subsetSEXP, SEXP n_shiftSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< size_t >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_subset(n_subsetSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_shift(n_shiftSEXP);
    rcpp_result_gen = Rcpp::wrap(shift_subset(x, lag, n_subset, n_shift));
    return rcpp_result_gen;
END_RCPP
}
// lag_list
List lag_list(const NumericVector& x, const IntegerVector& lags, size_t n_subset, size_t n_shift);
RcppExport SEXP _frecipes_lag_list(SEXP xSEXP, SEXP lagsSEXP, SEXP n_subsetSEXP, SEXP n_shiftSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type lags(lagsSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_subset(n_subsetSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_shift(n_shiftSEXP);
    rcpp_result_gen = Rcpp::wrap(lag_list(x, lags, n_subset, n_shift));
    return rcpp_result_gen;
END_RCPP
}
// scale_list_param_eigen
Rcpp::List scale_list_param_eigen(Rcpp::List x, Eigen::VectorXd center, Eigen::VectorXd scale);
RcppExport SEXP _frecipes_scale_list_param_eigen(SEXP xSEXP, SEXP centerSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type center(centerSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(scale_list_param_eigen(x, center, scale));
    return rcpp_result_gen;
END_RCPP
}
// cor_list_eigen
Eigen::MatrixXd cor_list_eigen(Rcpp::List x, Eigen::VectorXd center, Eigen::VectorXd scale);
RcppExport SEXP _frecipes_cor_list_eigen(SEXP xSEXP, SEXP centerSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type center(centerSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(cor_list_eigen(x, center, scale));
    return rcpp_result_gen;
END_RCPP
}
// pca_list_eigen
Rcpp::List pca_list_eigen(Rcpp::List x, Eigen::RowVectorXd center, Eigen::RowVectorXd scale, bool prep);
RcppExport SEXP _frecipes_pca_list_eigen(SEXP xSEXP, SEXP centerSEXP, SEXP scaleSEXP, SEXP prepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::RowVectorXd >::type center(centerSEXP);
    Rcpp::traits::input_parameter< Eigen::RowVectorXd >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< bool >::type prep(prepSEXP);
    rcpp_result_gen = Rcpp::wrap(pca_list_eigen(x, center, scale, prep));
    return rcpp_result_gen;
END_RCPP
}
// scale_list_matrix_eigen
Eigen::MatrixXd scale_list_matrix_eigen(const Rcpp::List x, bool center, bool scale);
RcppExport SEXP _frecipes_scale_list_matrix_eigen(SEXP xSEXP, SEXP centerSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type center(centerSEXP);
    Rcpp::traits::input_parameter< bool >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(scale_list_matrix_eigen(x, center, scale));
    return rcpp_result_gen;
END_RCPP
}
// pca_list_rotation_eigen
Eigen::MatrixXd pca_list_rotation_eigen(Rcpp::List x, Eigen::VectorXd center, Eigen::VectorXd scale, int n_comp);
RcppExport SEXP _frecipes_pca_list_rotation_eigen(SEXP xSEXP, SEXP centerSEXP, SEXP scaleSEXP, SEXP n_compSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type center(centerSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< int >::type n_comp(n_compSEXP);
    rcpp_result_gen = Rcpp::wrap(pca_list_rotation_eigen(x, center, scale, n_comp));
    return rcpp_result_gen;
END_RCPP
}
// pca_eigen
Rcpp::List pca_eigen(const Rcpp::List x, bool center, bool scale);
RcppExport SEXP _frecipes_pca_eigen(SEXP xSEXP, SEXP centerSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type center(centerSEXP);
    Rcpp::traits::input_parameter< bool >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(pca_eigen(x, center, scale));
    return rcpp_result_gen;
END_RCPP
}
// cor_eigen
Eigen::MatrixXd cor_eigen(Eigen::Map<Eigen::MatrixXd>& X);
RcppExport SEXP _frecipes_cor_eigen(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(cor_eigen(X));
    return rcpp_result_gen;
END_RCPP
}
// pca
Rcpp::List pca(Eigen::Map<Eigen::MatrixXd> x, bool center, bool scale);
RcppExport SEXP _frecipes_pca(SEXP xSEXP, SEXP centerSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type center(centerSEXP);
    Rcpp::traits::input_parameter< bool >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(pca(x, center, scale));
    return rcpp_result_gen;
END_RCPP
}
// pca_with_params
Rcpp::List pca_with_params(Eigen::Map<Eigen::MatrixXd> x, Eigen::RowVectorXd center, Eigen::RowVectorXd scale);
RcppExport SEXP _frecipes_pca_with_params(SEXP xSEXP, SEXP centerSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::RowVectorXd >::type center(centerSEXP);
    Rcpp::traits::input_parameter< Eigen::RowVectorXd >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(pca_with_params(x, center, scale));
    return rcpp_result_gen;
END_RCPP
}
// pca_list_with_params
Rcpp::List pca_list_with_params(Rcpp::List x, Eigen::RowVectorXd center, Eigen::RowVectorXd scale);
RcppExport SEXP _frecipes_pca_list_with_params(SEXP xSEXP, SEXP centerSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::RowVectorXd >::type center(centerSEXP);
    Rcpp::traits::input_parameter< Eigen::RowVectorXd >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(pca_list_with_params(x, center, scale));
    return rcpp_result_gen;
END_RCPP
}
// corEigen
Eigen::MatrixXd corEigen(Eigen::Map<Eigen::MatrixXd>& X);
RcppExport SEXP _frecipes_corEigen(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(corEigen(X));
    return rcpp_result_gen;
END_RCPP
}
// corEigen2
Eigen::MatrixXd corEigen2(Eigen::Map<Eigen::MatrixXd>& X);
RcppExport SEXP _frecipes_corEigen2(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(corEigen2(X));
    return rcpp_result_gen;
END_RCPP
}
// fi
IntegerVector fi(const NumericVector& x, const NumericVector& vec, const bool rightmost_closed, const bool all_inside, const bool left_open);
RcppExport SEXP _frecipes_fi(SEXP xSEXP, SEXP vecSEXP, SEXP rightmost_closedSEXP, SEXP all_insideSEXP, SEXP left_openSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< const bool >::type rightmost_closed(rightmost_closedSEXP);
    Rcpp::traits::input_parameter< const bool >::type all_inside(all_insideSEXP);
    Rcpp::traits::input_parameter< const bool >::type left_open(left_openSEXP);
    rcpp_result_gen = Rcpp::wrap(fi(x, vec, rightmost_closed, all_inside, left_open));
    return rcpp_result_gen;
END_RCPP
}
// to_dummy_list_base
Rcpp::IntegerVector to_dummy_list_base(const Rcpp::IntegerVector& x, const int n_fact);
RcppExport SEXP _frecipes_to_dummy_list_base(SEXP xSEXP, SEXP n_factSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const int >::type n_fact(n_factSEXP);
    rcpp_result_gen = Rcpp::wrap(to_dummy_list_base(x, n_fact));
    return rcpp_result_gen;
END_RCPP
}
// to_dummy_list
List to_dummy_list(const NumericVector& x, const NumericVector& vec, const bool rightmost_closed, const bool all_inside, const bool left_open);
RcppExport SEXP _frecipes_to_dummy_list(SEXP xSEXP, SEXP vecSEXP, SEXP rightmost_closedSEXP, SEXP all_insideSEXP, SEXP left_openSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< const bool >::type rightmost_closed(rightmost_closedSEXP);
    Rcpp::traits::input_parameter< const bool >::type all_inside(all_insideSEXP);
    Rcpp::traits::input_parameter< const bool >::type left_open(left_openSEXP);
    rcpp_result_gen = Rcpp::wrap(to_dummy_list(x, vec, rightmost_closed, all_inside, left_open));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_frecipes_b_spline_list", (DL_FUNC) &_frecipes_b_spline_list, 9},
    {"_frecipes_b_spline_list2", (DL_FUNC) &_frecipes_b_spline_list2, 9},
    {"_frecipes_b_spline_list3", (DL_FUNC) &_frecipes_b_spline_list3, 9},
    {"_frecipes_log_lags_arma", (DL_FUNC) &_frecipes_log_lags_arma, 2},
    {"_frecipes_distributed_lag_thread", (DL_FUNC) &_frecipes_distributed_lag_thread, 3},
    {"_frecipes_convolve_eigen", (DL_FUNC) &_frecipes_convolve_eigen, 2},
    {"_frecipes_distributed_lag_eigen", (DL_FUNC) &_frecipes_distributed_lag_eigen, 2},
    {"_frecipes_distributed_lag_thread_eigen", (DL_FUNC) &_frecipes_distributed_lag_thread_eigen, 6},
    {"_frecipes_distributed_lag_list", (DL_FUNC) &_frecipes_distributed_lag_list, 11},
    {"_frecipes_distributed_lag_list2", (DL_FUNC) &_frecipes_distributed_lag_list2, 11},
    {"_frecipes_distributed_lag_list3", (DL_FUNC) &_frecipes_distributed_lag_list3, 11},
    {"_frecipes_fft_matrix", (DL_FUNC) &_frecipes_fft_matrix, 2},
    {"_frecipes_convolve_vec", (DL_FUNC) &_frecipes_convolve_vec, 2},
    {"_frecipes_convolve_filter", (DL_FUNC) &_frecipes_convolve_filter, 4},
    {"_frecipes_convolve_overlap_add", (DL_FUNC) &_frecipes_convolve_overlap_add, 2},
    {"_frecipes_convolve_overlap_save", (DL_FUNC) &_frecipes_convolve_overlap_save, 2},
    {"_frecipes_convolve_overlap_save_list", (DL_FUNC) &_frecipes_convolve_overlap_save_list, 2},
    {"_frecipes_convolve_tf", (DL_FUNC) &_frecipes_convolve_tf, 2},
    {"_frecipes_convolve_matrix", (DL_FUNC) &_frecipes_convolve_matrix, 4},
    {"_frecipes_convolve_list", (DL_FUNC) &_frecipes_convolve_list, 4},
    {"_frecipes_convolve_list2", (DL_FUNC) &_frecipes_convolve_list2, 4},
    {"_frecipes_multiply_ffts", (DL_FUNC) &_frecipes_multiply_ffts, 1},
    {"_frecipes_fill_lower_left", (DL_FUNC) &_frecipes_fill_lower_left, 2},
    {"_frecipes_spec_pgram", (DL_FUNC) &_frecipes_spec_pgram, 5},
    {"_frecipes_spec_welch", (DL_FUNC) &_frecipes_spec_welch, 4},
    {"_frecipes_solve_cplx_parallel", (DL_FUNC) &_frecipes_solve_cplx_parallel, 1},
    {"_frecipes_solve_cplx_irr", (DL_FUNC) &_frecipes_solve_cplx_irr, 2},
    {"_frecipes_ordinary_coherence_phase", (DL_FUNC) &_frecipes_ordinary_coherence_phase, 1},
    {"_frecipes_transfer_pgram_smooth", (DL_FUNC) &_frecipes_transfer_pgram_smooth, 7},
    {"_frecipes_transfer_pgram", (DL_FUNC) &_frecipes_transfer_pgram, 5},
    {"_frecipes_transfer_welch", (DL_FUNC) &_frecipes_transfer_welch, 4},
    {"_frecipes_index_from_i_j", (DL_FUNC) &_frecipes_index_from_i_j, 3},
    {"_frecipes_get_column_number", (DL_FUNC) &_frecipes_get_column_number, 1},
    {"_frecipes_index_from_j_i", (DL_FUNC) &_frecipes_index_from_j_i, 3},
    {"_frecipes_next_n_eigen", (DL_FUNC) &_frecipes_next_n_eigen, 1},
    {"_frecipes_pad_vector", (DL_FUNC) &_frecipes_pad_vector, 3},
    {"_frecipes_detrend_matrix", (DL_FUNC) &_frecipes_detrend_matrix, 1},
    {"_frecipes_demean_matrix", (DL_FUNC) &_frecipes_demean_matrix, 1},
    {"_frecipes_detrend_and_demean_matrix", (DL_FUNC) &_frecipes_detrend_and_demean_matrix, 3},
    {"_frecipes_modified_daniell", (DL_FUNC) &_frecipes_modified_daniell, 1},
    {"_frecipes_kernel_apply", (DL_FUNC) &_frecipes_kernel_apply, 2},
    {"_frecipes_spec_taper", (DL_FUNC) &_frecipes_spec_taper, 2},
    {"_frecipes_make_groups", (DL_FUNC) &_frecipes_make_groups, 2},
    {"_frecipes_power_spaced", (DL_FUNC) &_frecipes_power_spaced, 4},
    {"_frecipes_group_frequency", (DL_FUNC) &_frecipes_group_frequency, 2},
    {"_frecipes_determine_frequency", (DL_FUNC) &_frecipes_determine_frequency, 1},
    {"_frecipes_check_ffts", (DL_FUNC) &_frecipes_check_ffts, 2},
    {"_frecipes_which_indices", (DL_FUNC) &_frecipes_which_indices, 2},
    {"_frecipes_window_hann", (DL_FUNC) &_frecipes_window_hann, 1},
    {"_frecipes_window_tukey", (DL_FUNC) &_frecipes_window_tukey, 2},
    {"_frecipes_window_hann_cplx", (DL_FUNC) &_frecipes_window_hann_cplx, 1},
    {"_frecipes_window_rectangle", (DL_FUNC) &_frecipes_window_rectangle, 1},
    {"_frecipes_window_first_deriv", (DL_FUNC) &_frecipes_window_first_deriv, 5},
    {"_frecipes_window_nuttall", (DL_FUNC) &_frecipes_window_nuttall, 1},
    {"_frecipes_window_blackman_nuttall", (DL_FUNC) &_frecipes_window_blackman_nuttall, 1},
    {"_frecipes_window_blackman_harris", (DL_FUNC) &_frecipes_window_blackman_harris, 1},
    {"_frecipes_window_scale", (DL_FUNC) &_frecipes_window_scale, 3},
    {"_frecipes_harmonic_list", (DL_FUNC) &_frecipes_harmonic_list, 4},
    {"_frecipes_check_lag", (DL_FUNC) &_frecipes_check_lag, 3},
    {"_frecipes_get_length", (DL_FUNC) &_frecipes_get_length, 2},
    {"_frecipes_get_start", (DL_FUNC) &_frecipes_get_start, 3},
    {"_frecipes_get_end", (DL_FUNC) &_frecipes_get_end, 4},
    {"_frecipes_shift_subset", (DL_FUNC) &_frecipes_shift_subset, 4},
    {"_frecipes_lag_list", (DL_FUNC) &_frecipes_lag_list, 4},
    {"_frecipes_scale_list_param_eigen", (DL_FUNC) &_frecipes_scale_list_param_eigen, 3},
    {"_frecipes_cor_list_eigen", (DL_FUNC) &_frecipes_cor_list_eigen, 3},
    {"_frecipes_pca_list_eigen", (DL_FUNC) &_frecipes_pca_list_eigen, 4},
    {"_frecipes_scale_list_matrix_eigen", (DL_FUNC) &_frecipes_scale_list_matrix_eigen, 3},
    {"_frecipes_pca_list_rotation_eigen", (DL_FUNC) &_frecipes_pca_list_rotation_eigen, 4},
    {"_frecipes_pca_eigen", (DL_FUNC) &_frecipes_pca_eigen, 3},
    {"_frecipes_cor_eigen", (DL_FUNC) &_frecipes_cor_eigen, 1},
    {"_frecipes_pca", (DL_FUNC) &_frecipes_pca, 3},
    {"_frecipes_pca_with_params", (DL_FUNC) &_frecipes_pca_with_params, 3},
    {"_frecipes_pca_list_with_params", (DL_FUNC) &_frecipes_pca_list_with_params, 3},
    {"_frecipes_corEigen", (DL_FUNC) &_frecipes_corEigen, 1},
    {"_frecipes_corEigen2", (DL_FUNC) &_frecipes_corEigen2, 1},
    {"_frecipes_fi", (DL_FUNC) &_frecipes_fi, 5},
    {"_frecipes_to_dummy_list_base", (DL_FUNC) &_frecipes_to_dummy_list_base, 2},
    {"_frecipes_to_dummy_list", (DL_FUNC) &_frecipes_to_dummy_list, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_frecipes(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
