# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' b_spline_list
#'
#' @description
#' Create spline terms
#'
#' @inheritParams splines2::bSpline
#' @param internal_knots locations where parameters can change
#' @param boundary_knots end points of the spline
#' @param complete_basis intercept argument
#'
#' @return List of distributed lags
#'
#' @export
#'
b_spline_list <- function(x, df, degree, internal_knots, boundary_knots, complete_basis = TRUE, periodic = FALSE, derivs = 0L, integral = FALSE) {
    .Call(`_frecipes_b_spline_list`, x, df, degree, internal_knots, boundary_knots, complete_basis, periodic, derivs, integral)
}

b_spline_list2 <- function(x, df, degree, internal_knots, boundary_knots, complete_basis = TRUE, periodic = FALSE, derivs = 0L, integral = FALSE) {
    .Call(`_frecipes_b_spline_list2`, x, df, degree, internal_knots, boundary_knots, complete_basis, periodic, derivs, integral)
}

b_spline_list3 <- function(x, df, degree, internal_knots, boundary_knots, complete_basis = TRUE, periodic = FALSE, derivs = 0L, integral = FALSE) {
    .Call(`_frecipes_b_spline_list3`, x, df, degree, internal_knots, boundary_knots, complete_basis, periodic, derivs, integral)
}

#' @title
#' log_lags_arma
#'
#' @description
#' Generate logarithmically spaced lags
#'
#' @param n integer number of lag terms
#' @param max_lag integer the maximum lag
#'
#' @return vector of logarithmically spaced lags
#'
#' @export
#'
log_lags_arma <- function(n, max_lag) {
    .Call(`_frecipes_log_lags_arma`, n, max_lag)
}

#' @title
#' be_clark_cpp
#'
#' @description
#' Clark 1967 solution for calculating barometric efficiency (Algorithm from Batu 1998, pg 76)
#'
#' @param dep \code{numeric vector} of the dependent variable (ie:water level)
#' @param ind \code{numeric vector} of the independent variable (ie:barometric pressure)
#' @param lag_space \code{integer} spacing for lags, useful for higher frequency monitoring
#' @param inverse \code{logical} whether the barometric relationship is inverse
#'
#' @return barometric efficiency using Clark's method
#'
#'
#' @export
#'
#' @examples
#' n <- 1000
#' baro <- sin(seq(0, 2*pi, length.out = 1000))
#' wl <- -0.4 * baro + rnorm(1000, sd = 0.02)
#' be_clark_cpp(wl, baro, lag_space=1, inverse=TRUE)
#'
be_clark_cpp <- function(dep, ind, lag_space, inverse) {
    .Call(`_frecipes_be_clark_cpp`, dep, ind, lag_space, inverse)
}

be_least_squares_diff_cpp <- function(dep, ind, lag_space, inverse) {
    .Call(`_frecipes_be_least_squares_diff_cpp`, dep, ind, lag_space, inverse)
}

be_least_squares_cpp <- function(dep, ind, inverse) {
    .Call(`_frecipes_be_least_squares_cpp`, dep, ind, inverse)
}

#' @title
#' be_acworth_calc_cpp
#'
#' @description
#' Acworth, R. I., Halloran, L. J. S., Rau, G. C., Cuthbert, M. O.,
#'  & Bernardi, T. L. (2016). An objective frequency-domain method for
#'   quantifying confined aquifer compressible storage using Earth and
#'   atmospheric tides. Geophysical Research Letters, 43(November).
#'   https://doi.org/10.1002/2016GL071328
#'
#' @param s2_gw \code{numeric} s2 component in the groundwater levels
#' @param s2_et \code{numeric} s2 component in the earth tides
#' @param s2_at \code{numeric} s2 component for atmospheric pressure
#' @param m2_gw \code{numeric} m2 component in the groundwater levels
#' @param m2_et \code{numeric} m2 component in the earth tides
#' @param d_phase \code{numeric} phase difference between Earth tide and atmospheric drivers s2_et and s2_at
#' @param inverse \code{logical} whether the barometric relationship is inverse (TRUE means that when the barometric pressure goes up the measured water level goes down (vented transducer, depth to water), FALSE means that when the barometric pressure goes up so does the measured pressure (non-vented transducer))
#'
#' @return barometric efficiency
#' @export
#'
#' @examples
#'
#' be_acworth_cpp(s2_at = 7.461,
#'            s2_et=224.640,
#'            s2_gw=4.086,
#'            m2_gw = 0.471,
#'            m2_et = 492.526,
#'            d_phase=-56.709,
#'            inverse = TRUE)
#' be_acworth_cpp(s2_at = 6.164,
#'            s2_et=270.463,
#'            s2_gw=0.329,
#'            m2_gw = 0.225,
#'            m2_et = 551.572,
#'            d_phase=-71.726,
#'            inverse = TRUE)
#' be_acworth_cpp(s2_at = 5.897,
#'            s2_et=234.478,
#'            s2_gw=5.536,
#'            m2_gw = 0.773,
#'            m2_et = 558.075,
#'            d_phase=-70.393,
#'            inverse = TRUE)
be_acworth_calc_cpp <- function(s2_gw, s2_et, s2_at, m2_gw, m2_et, d_phase, inverse) {
    .Call(`_frecipes_be_acworth_calc_cpp`, s2_gw, s2_et, s2_at, m2_gw, m2_et, d_phase, inverse)
}

get_peaks <- function(freqs, f1, f2) {
    .Call(`_frecipes_get_peaks`, freqs, f1, f2)
}

be_acworth_cpp <- function(x, spans, detrend, demean, taper, inverse, f1, f2, frequency_scale) {
    .Call(`_frecipes_be_acworth_cpp`, x, spans, detrend, demean, taper, inverse, f1, f2, frequency_scale)
}

a_cpp <- function(x) {
    .Call(`_frecipes_a_cpp`, x)
}

b_cpp <- function(x) {
    .Call(`_frecipes_b_cpp`, x)
}

c_cpp <- function(x) {
    .Call(`_frecipes_c_cpp`, x)
}

#' Calculate equations 4 and 5 from bouwer, 1989
#'
#' @param rw
#' @param Le
#' @param Lw
#' @param H
#'
#' @return ln(Re/rw)
#'
bouwer_rice_abc <- function(rw, Le, Lw, H) {
    .Call(`_frecipes_bouwer_rice_abc`, rw, Le, Lw, H)
}

#' Calculate transmissivity with Bouwer-Rice solution
#'
#' @param time the elapsed time
#' @param drawdown the drawdown
#' @param radius_screen radius of the screen
#' @param radius_casing radius of the casing where the water level is
#' @param Le
#' @param Lw
#' @param H
#'
#' @return transmissivity from bouwer_rice
#'
#' @export
bouwer_rice <- function(time, drawdown, radius_screen, radius_casing, Le, Lw, H) {
    .Call(`_frecipes_bouwer_rice`, time, drawdown, radius_screen, radius_casing, Le, Lw, H)
}

#' @title
#' distributed_lag_thread
#'
#' @description
#' Create distributed lag terms
#'
#' @param x
#' @param bl
#' @param n_thread
#'
#' @return List of distributed lags
#'
#' @export
#'
distributed_lag_thread <- function(x, bl, n_thread) {
    .Call(`_frecipes_distributed_lag_thread`, x, bl, n_thread)
}

convolve_eigen <- function(x, y) {
    .Call(`_frecipes_convolve_eigen`, x, y)
}

#' @title
#' distributed_lag_eigen
#'
#' @description
#' Create distributed lag terms
#'
#' @param x
#' @param bl
#'
#' @return List of distributed lags
#'
#' @export
#'
distributed_lag_eigen <- function(x, bl) {
    .Call(`_frecipes_distributed_lag_eigen`, x, bl)
}

#' @title
#' distributed_lag_thread_eigen
#'
#' @description
#' Create distributed lag terms
#'
#' @param x
#' @param bl
#' @param lag_max
#' @param n_subset
#' @param n_shift
#' @param n_thread
#'
#' @return List of distributed lags
#'
#' @export
#'
distributed_lag_thread_eigen <- function(x, bl, lag_max, n_subset, n_shift, n_thread) {
    .Call(`_frecipes_distributed_lag_thread_eigen`, x, bl, lag_max, n_subset, n_shift, n_thread)
}

#' @title
#' distributed_lag_list
#'
#' @description
#' Create distributed lag terms
#'
#' @param x
#' @param n_lag
#' @param max_lag
#' @param df
#' @param degree
#' @param internal_knots
#' @param boundary_knots
#' @param complete_basis
#' @param periodic
#' @param derivs
#' @param integral
#'
#' @return List of distributed lags
#'
#' @export
#'
distributed_lag_list <- function(x, n_lag, max_lag, df, degree, internal_knots, boundary_knots, complete_basis, periodic, derivs, integral) {
    .Call(`_frecipes_distributed_lag_list`, x, n_lag, max_lag, df, degree, internal_knots, boundary_knots, complete_basis, periodic, derivs, integral)
}

distributed_lag_list2 <- function(x, n_lag, max_lag, df, degree, internal_knots, boundary_knots, complete_basis, periodic, derivs, integral) {
    .Call(`_frecipes_distributed_lag_list2`, x, n_lag, max_lag, df, degree, internal_knots, boundary_knots, complete_basis, periodic, derivs, integral)
}

distributed_lag_list3 <- function(x, n_lag, max_lag, df, degree, internal_knots, boundary_knots, complete_basis, periodic, derivs, integral) {
    .Call(`_frecipes_distributed_lag_list3`, x, n_lag, max_lag, df, degree, internal_knots, boundary_knots, complete_basis, periodic, derivs, integral)
}

distributed_lag_list4 <- function(x, s, max_lag) {
    .Call(`_frecipes_distributed_lag_list4`, x, s, max_lag)
}

#' @title
NULL

#' @title
NULL

#' @title
NULL

#' @title
NULL

#' @title
NULL

#' @title
NULL

#' @title
NULL

#' @title
NULL

#' @title
NULL

#' @title
NULL

#' @title
NULL

#' @title
NULL

#' @title
NULL

#' @title
NULL

#' @title
NULL

#' @title
NULL

#' @title
NULL

#' @title
NULL

#' @title
#' fft_matrix
#'
#' @description
#' Do an FFT for each matrix column
#'
#' @param x the matrix that holds the series (numeric matrix)
#' @param detrend remove the linear trend of the columns (boolean)
#' @param demean remove the mean for each column (boolean)
#' @param n_new the padded size (integer)
#'
#' @return A matrix with FFT results.
#'
#' @noRd
#'
fft_matrix <- function(x, n_new) {
    .Call(`_frecipes_fft_matrix`, x, n_new)
}

convolve_vec <- function(x, y) {
    .Call(`_frecipes_convolve_vec`, x, y)
}

convolve_filter <- function(x, y, remove_partial, reverse) {
    .Call(`_frecipes_convolve_filter`, x, y, remove_partial, reverse)
}

convolve_overlap_add <- function(x, y) {
    .Call(`_frecipes_convolve_overlap_add`, x, y)
}

convolve_overlap_save <- function(x, y, align) {
    .Call(`_frecipes_convolve_overlap_save`, x, y, align)
}

shift_eigen <- function(x, n) {
    .Call(`_frecipes_shift_eigen`, x, n)
}

convolve_overlap_save_list <- function(x, y, align) {
    .Call(`_frecipes_convolve_overlap_save_list`, x, y, align)
}

convolve_tf <- function(x, y) {
    .Call(`_frecipes_convolve_tf`, x, y)
}

convolve_matrix <- function(x, y, remove_partial, reverse) {
    .Call(`_frecipes_convolve_matrix`, x, y, remove_partial, reverse)
}

convolve_list <- function(x, y, remove_partial, reverse) {
    .Call(`_frecipes_convolve_list`, x, y, remove_partial, reverse)
}

convolve_list2 <- function(x, y, remove_partial, reverse) {
    .Call(`_frecipes_convolve_list2`, x, y, remove_partial, reverse)
}

multiply_ffts <- function(x) {
    .Call(`_frecipes_multiply_ffts`, x)
}

fill_lower_left <- function(x, start) {
    .Call(`_frecipes_fill_lower_left`, x, start)
}

spec_pgram <- function(x, spans, detrend, demean, taper) {
    .Call(`_frecipes_spec_pgram`, x, spans, detrend, demean, taper)
}

spec_pgram_list <- function(x, spans, detrend, demean, taper) {
    .Call(`_frecipes_spec_pgram_list`, x, spans, detrend, demean, taper)
}

spec_welch <- function(x, length_subset, overlap, window) {
    .Call(`_frecipes_spec_welch`, x, length_subset, overlap, window)
}

solve_cplx_parallel <- function(x) {
    .Call(`_frecipes_solve_cplx_parallel`, x)
}

list_to_matrix <- function(x, sub_start, sub_end) {
    .Call(`_frecipes_list_to_matrix`, x, sub_start, sub_end)
}

solve_cplx_irr <- function(x, n_groups) {
    .Call(`_frecipes_solve_cplx_irr`, x, n_groups)
}

ordinary_coherence_phase <- function(x) {
    .Call(`_frecipes_ordinary_coherence_phase`, x)
}

transfer_pgram_smooth <- function(x, spans, detrend, demean, taper, power, n_groups) {
    .Call(`_frecipes_transfer_pgram_smooth`, x, spans, detrend, demean, taper, power, n_groups)
}

transfer_pgram <- function(x, spans, detrend, demean, taper) {
    .Call(`_frecipes_transfer_pgram`, x, spans, detrend, demean, taper)
}

transfer_welch <- function(x, length_subset, overlap, window) {
    .Call(`_frecipes_transfer_welch`, x, length_subset, overlap, window)
}

#' @title
#' window_hann
#'
#' @description
#' Hann window for FFT.
#'
#' @param n length of the window vector (integer)
#'
#' @return window of length n.
#'
#' @noRd
#'
window_hann <- function(n) {
    .Call(`_frecipes_window_hann`, n)
}

#' @title
#' window_tukey
#'
#' @description
#' Tukey window for FFT.
#'
#' @inheritParams window_hann
#' @param r percent on each side to taper (double)
#'
#' @return window of length n.
#'
#' @noRd
#'
window_tukey <- function(n, r) {
    .Call(`_frecipes_window_tukey`, n, r)
}

#' @title
#' window_hann_cplx
#'
#' @description
#' Hann window for complex FFT.
#'
#' @inheritParams window_hann
#'
#' @return window of length n.
#'
#' @noRd
#'
window_hann_cplx <- function(n) {
    .Call(`_frecipes_window_hann_cplx`, n)
}

#' @title
#' window_rectangle
#'
#' @description
#' Rectangular window.
#'
#' @inheritParams window_hann
#'
#' @return window of length n.
#'
#' @noRd
#'
window_rectangle <- function(n) {
    .Call(`_frecipes_window_rectangle`, n)
}

#' @title
#' window_first_deriv
#'
#' @description
#' First derivative window for FFT
#'
#' @inheritParams window_hann
#'
#' @param a0 \code{double} coefficient
#' @param a1 \code{double} coefficient
#' @param a2 \code{double} coefficient
#' @param a3 \code{double} coefficient
#'
#' @return window
#'
#' @export
#'
#' @examples
#' # nuttall window
#' window_first_deriv(100, 0.355768, 0.487396, 0.144232, 0.012604)
#'
#' @noRd
#'
window_first_deriv <- function(n, a0, a1, a2, a3) {
    .Call(`_frecipes_window_first_deriv`, n, a0, a1, a2, a3)
}

#' @title
#' window_nuttall
#'
#' @description
#' Nuttall window for FFT
#'
#' @inheritParams window_hann
#'
#' @return window
#'
#' @export
#'
#' @examples
#' window_nuttall(100)
#'
#' @noRd
#'
window_nuttall <- function(n) {
    .Call(`_frecipes_window_nuttall`, n)
}

#' @title
#' window_blackman_nuttall
#'
#' @description
#' Blackman-Nuttall window for FFT
#'
#' @inheritParams window_hann
#'
#' @return window
#'
#' @export
#'
#' @examples
#' window_blackman_nuttall(100)
#'
#' @noRd
#'
window_blackman_nuttall <- function(n) {
    .Call(`_frecipes_window_blackman_nuttall`, n)
}

#' @title
#' window_blackman_harris
#'
#' @description
#' Blackman-Harris window for FFT
#'
#' @inheritParams window_hann
#'
#' @return window
#'
#' @export
#'
#' @examples
#' window_blackman_harris(100)
#'
#' @noRd
#'
window_blackman_harris <- function(n) {
    .Call(`_frecipes_window_blackman_harris`, n)
}

#' @title
#' window_scale
#'
#' @description
#' Scale factor for a window function.
#'
#' @param window the window function (numeric vector)
#' @param n_new length of the padded series (integer)
#' @param n_fft length of the input series (integer)
#'
#' @return window of length n.
#'
#' @noRd
#'
window_scale <- function(window, n_new, n_fft) {
    .Call(`_frecipes_window_scale`, window, n_new, n_fft)
}

gwr_p <- function(time, n_gwr) {
    .Call(`_frecipes_gwr_p`, time, n_gwr)
}

barker_herbert_impulse <- function(p, radius, radius_patch, t_1, t_2, s_1, s_2) {
    .Call(`_frecipes_barker_herbert_impulse`, p, radius, radius_patch, t_1, t_2, s_1, s_2)
}

gwr_barker_herbert <- function(time, flow_rate, radius, radius_patch, t_1, t_2, s_1, s_2, n_gwr) {
    .Call(`_frecipes_gwr_barker_herbert`, time, flow_rate, radius, radius_patch, t_1, t_2, s_1, s_2, n_gwr)
}

#' @title
#' grf_time
NULL

#' @title
NULL

impulse_function <- function(u) {
    .Call(`_frecipes_impulse_function`, u)
}

impulse_function_rcpp <- function(u) {
    .Call(`_frecipes_impulse_function_rcpp`, u)
}

impulse_function_eigen <- function(u) {
    .Call(`_frecipes_impulse_function_eigen`, u)
}

exp_int <- function(u) {
    .Call(`_frecipes_exp_int`, u)
}

binary_search <- function(x, y) {
    .Call(`_frecipes_binary_search`, x, y)
}

std_to_eigen <- function(u) {
    .Call(`_frecipes_std_to_eigen`, u)
}

eigen_to_std <- function(u) {
    .Call(`_frecipes_eigen_to_std`, u)
}

std_to_rcpp <- function(u) {
    .Call(`_frecipes_std_to_rcpp`, u)
}

rcpp_to_std <- function(u) {
    .Call(`_frecipes_rcpp_to_std`, u)
}

calculate_distance <- function(x_well, y_well, x_loc, y_loc) {
    .Call(`_frecipes_calculate_distance`, x_well, y_well, x_loc, y_loc)
}

well_function_coefficient <- function(flow_rate, transmissivity) {
    .Call(`_frecipes_well_function_coefficient`, flow_rate, transmissivity)
}

well_function_coefficient_vec <- function(flow_rate, transmissivity) {
    .Call(`_frecipes_well_function_coefficient_vec`, flow_rate, transmissivity)
}

well_function_coefficient_rcpp <- function(flow_rate, transmissivity) {
    .Call(`_frecipes_well_function_coefficient_rcpp`, flow_rate, transmissivity)
}

theis_u <- function(radius, storativity, transmissivity, time) {
    .Call(`_frecipes_theis_u`, radius, storativity, transmissivity, time)
}

theis_u_time_vec <- function(radius, storativity, transmissivity, time) {
    .Call(`_frecipes_theis_u_time_vec`, radius, storativity, transmissivity, time)
}

theis_u_time_rcpp <- function(radius, storativity, transmissivity, time) {
    .Call(`_frecipes_theis_u_time_rcpp`, radius, storativity, transmissivity, time)
}

grf_coefficient <- function(radius, hydraulic_conductivity, thickness, flow_dimension) {
    .Call(`_frecipes_grf_coefficient`, radius, hydraulic_conductivity, thickness, flow_dimension)
}

grf_u <- function(radius, specific_storage, hydraulic_conductivity) {
    .Call(`_frecipes_grf_u`, radius, specific_storage, hydraulic_conductivity)
}

grf_time <- function(radius, specific_storage, hydraulic_conductivity, thickness, time, flow_rate, flow_dimension) {
    .Call(`_frecipes_grf_time`, radius, specific_storage, hydraulic_conductivity, thickness, time, flow_rate, flow_dimension)
}

grf_grid <- function(grid, well_locations, flow_rate, time, specific_storage, hydraulic_conductivity, thickness, flow_dimension) {
    .Call(`_frecipes_grf_grid`, grid, well_locations, flow_rate, time, specific_storage, hydraulic_conductivity, thickness, flow_dimension)
}

hantush_epsilon <- function(radius, leakage) {
    .Call(`_frecipes_hantush_epsilon`, radius, leakage)
}

#' @title
#' hantush_well_single
#'
#' @description
#' Result of the hantush well function
#'
#' J.H.A. Prodanoff; W.J. Mansur; F.C.B. Mascarenhas (2006). Numerical
#' evaluation of Theis and Hantush-Jacob well functions. , 318(1-4),
#' 0–183. doi:10.1016/j.jhydrol.2005.05.026 eq: 10, 11, 12
#'
#'
#' @param u value of the Theis u
#' @param b the leakance
#' @param n_terms the number of terms used in the hantush approximation
#'
#'
#' @return hantush well function
#'
#'
#' @export
#'
hantush_well <- function(u, b, precision) {
    .Call(`_frecipes_hantush_well`, u, b, precision)
}

hantush_well_vec <- function(u, b, n_terms) {
    .Call(`_frecipes_hantush_well_vec`, u, b, n_terms)
}

hantush_well_rcpp <- function(u, b, precision) {
    .Call(`_frecipes_hantush_well_rcpp`, u, b, precision)
}

#' @title
#' hantush_jacob
#'
#' @description
#' Convolution of hantush well function and flow rates in the time domain.
#' Time series needs to be regularly spaced.
#'
#' @param radius distance to monitoring interval
#' @param storativity aquifer storativity
#' @param transmissivity aquifer transmissivity
#' @param leakage hantush leakage
#' @param time prediction times
#' @param flow_rate well flow rates
#' @param flow_time_interval time between flow rate measurements in samples
#' @param n_terms number of terms to use in Hantush solution.  More is more precise but slower.
#'
#' @return hantush jacob solution for multiple pumping scenario
#'
#'
#' @export
#'
hantush_jacob <- function(time, flow_rate, radius, storativity, transmissivity, leakage, precision) {
    .Call(`_frecipes_hantush_jacob`, time, flow_rate, radius, storativity, transmissivity, leakage, precision)
}

#' @title
#' harmonic_list
#'
#' @description
#' Create sin and cosine terms for harmonic analysis
#'
#' @param time numeric vector of times
#' @param frequency numeric vector of frequencies
#' @param start time the cycle starts
#' @param cycle_size size of the cycle in number of measurements
#'
#' @return List of sines and cosines
#'
#' @export
#'
harmonic_list <- function(time, frequency, start, cycle_size) {
    .Call(`_frecipes_harmonic_list`, time, frequency, start, cycle_size)
}

any_decimal <- function(x) {
    .Call(`_frecipes_any_decimal`, x)
}

decimal_to_scaled_integer <- function(x) {
    .Call(`_frecipes_decimal_to_scaled_integer`, x)
}

gcd <- function(x) {
    .Call(`_frecipes_gcd`, x)
}

#' @title
#' index_from_i_j
#'
#' @description
#' Get the column number for the cross-spectra matrix.
#'
#' @param i row number (integer)
#' @param i column number (integer)
#' @param n_col the number of columns i.e. the number of covariates. (integer)
#'
#' @return integer value containing the column number of the cross-spectra.
#'
#' @noRd
#'
index_from_i_j <- function(i, j, n_col) {
    .Call(`_frecipes_index_from_i_j`, i, j, n_col)
}

get_column_number <- function(n) {
    .Call(`_frecipes_get_column_number`, n)
}

#' @title
#' index_from_j_i
#'
#' @description
#' Get the column number for the cross-spectra matrix.
#'
#' @inheritParams index_from_i_j
#'
#' @return integer value containing the column number of the cross-spectra
#' conjugate term.
#'
#' @noRd
#'
index_from_j_i <- function(i, j, n_col) {
    .Call(`_frecipes_index_from_j_i`, i, j, n_col)
}

#' @title
#' next_n_eigen
#'
#' @description
#' Get the size of the nearest fast length for an FFT. This just uses the base
#' function right now.
#'
#' @inheritParams nextn
#'
#' @return 'nice' integer value for the length of the padded FFT.
#'
#' @noRd
#'
next_n_eigen <- function(n) {
    .Call(`_frecipes_next_n_eigen`, n)
}

#' @title
#' pad_vector
#'
#' @description
#' Pad a vector with zeros to a desired length.
#'
#' @param x initial vector to pad (numeric vector)
#' @param x_old initial length of vector (integer)
#' @param x_new desired length of padded vector (integer)
#'
#' @return 'nice' integer value for the length of the padded FFT.
#'
#' @noRd
#'
pad_vector <- function(x, n_old, n_new) {
    .Call(`_frecipes_pad_vector`, x, n_old, n_new)
}

#' @title
#' detrend_matrix
#'
#' @description
#' Linearly detrend the columns of a matrix. This is translated from spec.pgram
#'
#' @param x the matrix that holds multiple series (numeric matrix)
#'
#' @return columns of a matrix that have been linearly detrended.
#'
#' @noRd
#'
detrend_matrix <- function(x) {
    .Call(`_frecipes_detrend_matrix`, x)
}

#' @title
#' detrend_vector
#'
#' @description
#' Linearly detrend the columns of a matrix. This is translated from spec.pgram
#'
#' @param x the matrix that holds multiple series (numeric matrix)
#'
#' @return columns of a matrix that have been linearly detrended.
#'
#' @noRd
#'
detrend_vector <- function(x) {
    .Call(`_frecipes_detrend_vector`, x)
}

#' @title
#' demean_matrix
#'
#' @description
#' Remove the mean from each column of a matrix.
#'
#' @inheritParams detrend_matrix
#'
#' @return columns of a matrix with the means removed.
#'
#' @noRd
#'
demean_matrix <- function(x) {
    .Call(`_frecipes_demean_matrix`, x)
}

#' @title
#' demean_matrix
#'
#' @description
#' Remove the mean from each column of a matrix.
#'
#' @inheritParams detrend_matrix
#'
#' @return columns of a matrix with the means removed.
#'
#' @noRd
#'
demean_vector <- function(x) {
    .Call(`_frecipes_demean_vector`, x)
}

#' @title
#' detrend_and_demean_matrix
#'
#' @description
#' Remove the trend and mean from each column of a matrix.
#'
#' @inheritParams detrend_matrix
#' @param detrend should the trend be removed from each column (boolean)
#' @param demean should the mean be removed from each column (boolean)
#'
#' @return columns of a matrix with the means and/or trends removed.
#'
#' @noRd
#'
detrend_and_demean_matrix <- function(x, detrend, demean) {
    .Call(`_frecipes_detrend_and_demean_matrix`, x, detrend, demean)
}

#' @title
#' detrend_and_demean_list
#'
#' @description
#' Remove the trend and mean from each column of a matrix.
#'
#' @inheritParams detrend_matrix
#' @param detrend should the trend be removed from each column (boolean)
#' @param demean should the mean be removed from each column (boolean)
#'
#' @return columns of a matrix with the means and/or trends removed.
#'
#' @noRd
#'
detrend_and_demean_list <- function(x, detrend, demean) {
    .Call(`_frecipes_detrend_and_demean_list`, x, detrend, demean)
}

#' @title
#' modified_daniell
#'
#' @description
#' Create a modified daniell kernel using FFT. Adapted from `spec.pgram`.
#'
#' @inheritParams spec.pgram
#'
#' @param n length of the kernel (integer)
#'
#' @return modified Daniell kernel.
#'
#' @noRd
#'
modified_daniell <- function(spans) {
    .Call(`_frecipes_modified_daniell`, spans)
}

#' @title
#' kernel_apply
#'
#' @description
#' Create a modified daniell kernel using FFT. Adapted from `spec.pgram`. This
#' only calculates the upper triangle when truncated is FALSE.  When truncated
#' is TRUE the first row is skipped.
#'
#' @inheritParams spec.pgram
#'
#'
#' @return modified Daniell kernel.
#'
#' @noRd
#'
kernel_apply <- function(x, y) {
    .Call(`_frecipes_kernel_apply`, x, y)
}

#' @title
#' kernel_apply
#'
#' @description
#' Create a modified daniell kernel using FFT. Adapted from `spec.pgram`. This
#' only calculates the upper triangle when truncated is FALSE.  When truncated
#' is TRUE the first row is skipped.
#'
#' @inheritParams spec.pgram
#'
#'
#' @return modified Daniell kernel.
#'
#' @noRd
#'
kernel_apply_list <- function(x, y) {
    .Call(`_frecipes_kernel_apply_list`, x, y)
}

#' @title
#' spec_taper
#'
#' @description
#' Create a cosine-bell taper. Adapted from `spec.taper`.
#'
#' @inheritParams spec.taper
#'
#'
#' @return cosine-bell taper.
#'
#' @noRd
#'
spec_taper <- function(n_row, p) {
    .Call(`_frecipes_spec_taper`, n_row, p)
}

#' @title
#' make_groups
#'
#' @description
#' Create a set of lengths with increasing sizes useful from grouping results.
#' The first and last groups have length equal to 1.
#'
#' @param n the number of values to subset into groups. (integer)
#' @param max_lag how fast groups get bigger. Larger numbers have a larger range
#' of group sizes. (integer)
#' @param n_groups the number of groups to create. (integer)
#' @param min_aggregate the minimum size for a group. (integer)
#'
#'
#' @return Matrix with filled in complex conjugate columns.
#'
#' @noRd
#'
make_groups <- function(n_groups, n) {
    .Call(`_frecipes_make_groups`, n_groups, n)
}

#' @title
#' power_spaced
#'
#' @description
#' Create an n length vector of power spaced series between min and max.
#'
#' @param n the number of values. (integer)
#' @param min minimum value in series. (integer)
#' @param max maximum value in series. (integer)
#' @param power how fast values change. (integer)
#'
#'
#' @return vector of power spaced series between min and max.
#'
#' @noRd
#'
power_spaced <- function(n, min, max, power) {
    .Call(`_frecipes_power_spaced`, n, min, max, power)
}

#' @title
#' group_frequency
#'
#' @description
#' Get the mean frequency for each group.
#'
#' @inheritParams make_groups
#'
#' @param frequency vector of frequencies. (integer)
#'
#'
#' @return vector frequencies for each group.
#'
#' @noRd
#'
group_frequency <- function(frequencies, n_groups) {
    .Call(`_frecipes_group_frequency`, frequencies, n_groups)
}

#' @title
#' determine_frequency
#'
#' @description
#' Get frequencies based on series length
#'
#'
#' @param n length of series. (integer)
#'
#'
#' @return vector of frequencies between 0 and 0.5.
#'
#' @noRd
#'
determine_frequency <- function(n) {
    .Call(`_frecipes_determine_frequency`, n)
}

check_ffts <- function(x, cutoff) {
    .Call(`_frecipes_check_ffts`, x, cutoff)
}

#' @title
#' which_indices
#'
#' @description
#' Determine the intervals that each x value falls in
#'
#' @inheritParams splines::bs
#' @param knots location of knots for the b-splines. Unlike `splines::bs` this
#' includes the boundary knots. (numeric vector)
#'
#'
#' @return the interval ids that each x value falls in.
#'
#' @noRd
#'
which_indices <- function(x, knots) {
    .Call(`_frecipes_which_indices`, x, knots)
}

gamma_inc <- function(u, a) {
    .Call(`_frecipes_gamma_inc`, u, a)
}

#' @title
#' bessel_k_cplx
#'
#' @description
#' Modified Bessel function of first kind order 1
#'
#' @param x \code{numeric} value to evaluate
#' @param nu \code{numeric} value to evaluate
#' @param expon_scaled \code{boolean} value to evaluate
#' @param n_seq \code{nseq} value to evaluate
#'
#' @return bessel function result
#'
#'
#' @export
bessel_k_cplx <- function(x, nu, expon_scaled, n_seq) {
    .Call(`_frecipes_bessel_k_cplx`, x, nu, expon_scaled, n_seq)
}

stehfest_v <- function(n) {
    .Call(`_frecipes_stehfest_v`, n)
}

stehfest_p <- function(time, n_terms) {
    .Call(`_frecipes_stehfest_p`, time, n_terms)
}

cohen_p <- function(time, n_terms) {
    .Call(`_frecipes_cohen_p`, time, n_terms)
}

cohen_c <- function(d, n_terms) {
    .Call(`_frecipes_cohen_c`, d, n_terms)
}

cooper_bredehoeft_papadopulos_laplace <- function(time, r, r_c, r_w, Tr, S, h_0, n_terms) {
    .Call(`_frecipes_cooper_bredehoeft_papadopulos_laplace`, time, r, r_c, r_w, Tr, S, h_0, n_terms)
}

papadopulos_cooper_laplace <- function(time, Q, r, r_c, r_w, Tr, S, prec, n_terms) {
    .Call(`_frecipes_papadopulos_cooper_laplace`, time, Q, r, r_c, r_w, Tr, S, prec, n_terms)
}

jacob_lohman_laplace <- function(time, s, r, Tr, S, prec, n_terms) {
    .Call(`_frecipes_jacob_lohman_laplace`, time, s, r, Tr, S, prec, n_terms)
}

hantush_jacob_laplace <- function(time, c, r, Tr, S, Q, prec, n_terms) {
    .Call(`_frecipes_hantush_jacob_laplace`, time, c, r, Tr, S, Q, prec, n_terms)
}

barker_herbert <- function(time, radius, radius_patch, t_1, t_2, s_1, s_2, Q, prec, n_terms) {
    .Call(`_frecipes_barker_herbert`, time, radius, radius_patch, t_1, t_2, s_1, s_2, Q, prec, n_terms)
}

parallel_fractures_solute <- function(time, z, x, concentration_influent, time_influent, c_0, b, B, v, alpha_l, D_star, k_f, k_m, t_half, rho_b, theta, tortuosity, n_terms) {
    .Call(`_frecipes_parallel_fractures_solute`, time, z, x, concentration_influent, time_influent, c_0, b, B, v, alpha_l, D_star, k_f, k_m, t_half, rho_b, theta, tortuosity, n_terms)
}

parallel_fractures_heat <- function(time, z, x, temperature_influent, time_influent, t_0, b, B, v, lambda_fracture, lambda_matrix, spec_heat_w, spec_heat_s, rho_w, rho_s, theta, n_terms) {
    .Call(`_frecipes_parallel_fractures_heat`, time, z, x, temperature_influent, time_influent, t_0, b, B, v, lambda_fracture, lambda_matrix, spec_heat_w, spec_heat_s, rho_w, rho_s, theta, n_terms)
}

#' @title
NULL

check_lag <- function(n, lag, n_shift) {
    .Call(`_frecipes_check_lag`, n, lag, n_shift)
}

get_length <- function(n, n_subset) {
    .Call(`_frecipes_get_length`, n, n_subset)
}

get_start <- function(n_out, lag, n_subset) {
    .Call(`_frecipes_get_start`, n_out, lag, n_subset)
}

get_end <- function(n, n_out, lag, n_subset) {
    .Call(`_frecipes_get_end`, n, n_out, lag, n_subset)
}

shift_subset <- function(x, lag, n_subset, n_shift) {
    .Call(`_frecipes_shift_subset`, x, lag, n_subset, n_shift)
}

#' @title
#' lag_list
#'
#' @description
#' Create lagged terms
#'
#' @param x
#' @param lags
#' @param n_subset
#' @param n_shift
#'
#' @return List of lagged terms
#'
#' @export
#'
lag_list <- function(x, lags, n_subset, n_shift) {
    .Call(`_frecipes_lag_list`, x, lags, n_subset, n_shift)
}

llt_solve <- function(X, Y) {
    .Call(`_frecipes_llt_solve`, X, Y)
}

llt_fitted <- function(X, Y) {
    .Call(`_frecipes_llt_fitted`, X, Y)
}

#' @title
#' Ogata-Banks solution for 1-D flow.
#'
#' @description
#' Ogata, A., Banks, R.B., 1961. A solution of the differential equation of
#' longitudinal dispersion in porous media. U. S. Geol. Surv. Prof. Pap. 411-A.
#' 1-D, infinite source, uniform flow, constant parameters, no decay, no retardation
#'
#' @param D diffusion coefficient
#' @param v double velocity
#' @param C0 double concentration
#' @param x double x position
#' @param t double time
#'
#' @return ogata banks solution
#'
#' @export
#'
ogata_banks_ind <- function(D, v, C0, x, t) {
    .Call(`_frecipes_ogata_banks_ind`, D, v, C0, x, t)
}

ogata_banks_vec <- function(D, v, C0, x, t) {
    .Call(`_frecipes_ogata_banks_vec`, D, v, C0, x, t)
}

ogata_banks_decay_ind <- function(c0, v, D, R, k, x, t) {
    .Call(`_frecipes_ogata_banks_decay_ind`, c0, v, D, R, k, x, t)
}

ogata_banks_decay_vec <- function(c0, v, D, R, k, x, t) {
    .Call(`_frecipes_ogata_banks_decay_vec`, c0, v, D, R, k, x, t)
}

scale_list_param <- function(x, center, scale) {
    .Call(`_frecipes_scale_list_param`, x, center, scale)
}

scale_list_param_std <- function(x, center, scale) {
    .Call(`_frecipes_scale_list_param_std`, x, center, scale)
}

scale_list_param_eigen <- function(x, center, scale) {
    .Call(`_frecipes_scale_list_param_eigen`, x, center, scale)
}

cor_list_eigen <- function(x, center, scale) {
    .Call(`_frecipes_cor_list_eigen`, x, center, scale)
}

pca_list_eigen <- function(x, center, scale, prep = TRUE) {
    .Call(`_frecipes_pca_list_eigen`, x, center, scale, prep)
}

scale_list_matrix_eigen <- function(x, center = TRUE, scale = TRUE) {
    .Call(`_frecipes_scale_list_matrix_eigen`, x, center, scale)
}

pca_list_rotation_eigen <- function(x, center, scale, n_comp) {
    .Call(`_frecipes_pca_list_rotation_eigen`, x, center, scale, n_comp)
}

pca_eigen <- function(x, center = TRUE, scale = TRUE) {
    .Call(`_frecipes_pca_eigen`, x, center, scale)
}

cor_eigen <- function(X) {
    .Call(`_frecipes_cor_eigen`, X)
}

pca <- function(x, center = TRUE, scale = TRUE) {
    .Call(`_frecipes_pca`, x, center, scale)
}

pca_with_params <- function(x, center, scale) {
    .Call(`_frecipes_pca_with_params`, x, center, scale)
}

pca_list_with_params <- function(x, center, scale) {
    .Call(`_frecipes_pca_list_with_params`, x, center, scale)
}

fi <- function(x, vec, rightmost_closed, all_inside, left_open) {
    .Call(`_frecipes_fi`, x, vec, rightmost_closed, all_inside, left_open)
}

to_dummy_list_base <- function(x, n_fact) {
    .Call(`_frecipes_to_dummy_list_base`, x, n_fact)
}

#' @title
#' to_dummy
#'
#' @description
#' Create binary terms based on a factor column.
#'
#' @params ind integer vector of values to dummy encode
#'
#' @return List of dummy encoded terms
#'
#' @export
#'
#'
to_dummy <- function(ind, one_hot) {
    .Call(`_frecipes_to_dummy`, ind, one_hot)
}

#' @title
#' to_dummy_list
#'
#' @description
#' Create binary terms based on intervals. This function uses `findInterval`,
#' followed by a conversion to dummy encoding.
#'
#' @inheritParams findInterval
#'
#' @return List of dummy encoded terms
#'
#' @export
#'
#'
to_dummy_list <- function(x, vec, one_hot = FALSE, rightmost_closed = FALSE, all_inside = FALSE, left_open = FALSE) {
    .Call(`_frecipes_to_dummy_list`, x, vec, one_hot, rightmost_closed, all_inside, left_open)
}

weeks_1979 <- function(lag, D, L, precision, inverse) {
    .Call(`_frecipes_weeks_1979`, lag, D, L, precision, inverse)
}

#' @title
#' vadose_response
#'
#' @description
#' weeks_1979 1-D air diffusivity
#'
#' @param time numeric vector of elapsed times
#' @param air_diffusivity A numeric value of the unsaturated zone air diffusivity
#' @param thickness A numeric value of the unsaturated zone thickness
#' @param precision A numeric value of for the solution precision
#' @param inverse A logical value indicating if an inverse water level relationship is desired
#'
#' @return weeks 1979 model
#'
#'
#' @export
#'
#' @examples
#' vr <- vadose_response(time = 0:43200,
#'                        air_diffusivity = 0.20,
#'                        thickness = 40,
#'                        precision = 1e-10,
#'                        inverse = FALSE)
vadose_response <- function(time, air_diffusivity, thickness, precision, inverse) {
    .Call(`_frecipes_vadose_response`, time, air_diffusivity, thickness, precision, inverse)
}

vadose_response2 <- function(time, air_diffusivity, thickness, precision, inverse) {
    .Call(`_frecipes_vadose_response2`, time, air_diffusivity, thickness, precision, inverse)
}

